-- phpMyAdmin SQL Dump
-- version 4.9.0.1
-- https://www.phpmyadmin.net/
--
-- Host: sql104.epizy.com
-- Generation Time: Mar 15, 2023 at 12:28 PM
-- Server version: 10.4.17-MariaDB
-- PHP Version: 7.2.22

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `epiz_32471853_RadioNoise`
--

-- --------------------------------------------------------

--
-- Table structure for table `cadastro`
--

CREATE TABLE `cadastro` (
  `idlogin` int(11) NOT NULL,
  `nome` varchar(100) NOT NULL,
  `email` varchar(255) NOT NULL,
  `senha` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `cadastro`
--

INSERT INTO `cadastro` (`idlogin`, `nome`, `email`, `senha`) VALUES
(9, 'Isabella', 'isabellafernandez200@gmail.com', 'isa123'),
(10, 'Pedro ', 'pdrcaliel@gmail.com', '0000'),
(11, 'Neres', 'N25@gmail.com', 'senha123'),
(12, 'IsaaÃ¡', 'umemailaleatorio@gmail.com', '123456'),
(13, 'Victor valentim', 'valentimvictor628@gmail.com', '12340987'),
(14, 'Felipe Lopes de Oliveira ', 'felipelopesoliveira45@gmail.com', 'felipelopes01062006'),
(15, 'Teles', 'teles@gmail.com', 'senhasecreta'),
(16, 'Raul', 'Raulsouza', '123'),
(17, 'Cleiotn', 'seuemial@gmailcom', 'senha'),
(19, 'Pedro Henrique', 'baitolavini413@gmail.com', 'VINIBAITOLAO'),
(22, 'Gabriel ', 'Gabriel@gmail.com', '123'),
(26, 'asdf', 'jonas@jonas.com', '123'),
(28, 'bola', 'bolabolabola@gmail.com', '12345'),
(31, 'Lucas', 'lucasricard.silva@gmail.com', 'sacul369'),
(32, 'Teste', 'teste@email.com', '123'),
(39, 'Leonardo', 'gogobobo599@gmail.com', '123'),
(58, 'ae', 'ae', 'ae'),
(59, 'asdfasdf', 'boulos@boulos.com', '123'),
(61, 'gepa', 'gepaaaa@email.com', '123'),
(63, 'ae', 'sasdf@asdfgasd.com', '123'),
(65, 'gepa', 'testessd@email.com', '123'),
(67, 'gepa', 'testesad@email.com', '123'),
(74, 'gepa', 'testesadasd@email.com', '123'),
(80, 'Teste', 'teste@teste.com', 'teste'),
(81, 'Teste', 'Testeee', '1234');

-- --------------------------------------------------------

--
-- Table structure for table `receitas`
--

CREATE TABLE `receitas` (
  `idreceitas` int(11) NOT NULL,
  `nome` varchar(100) NOT NULL,
  `tipo` varchar(25) NOT NULL,
  `ingredientes` text NOT NULL,
  `modo_preparo` longtext NOT NULL,
  `carboidrato` float NOT NULL,
  `proteinas` float NOT NULL,
  `gorduras` float NOT NULL,
  `calorias` int(11) NOT NULL,
  `imagem` varchar(255) NOT NULL,
  `loginid` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `receitas`
--

INSERT INTO `receitas` (`idreceitas`, `nome`, `tipo`, `ingredientes`, `modo_preparo`, `carboidrato`, `proteinas`, `gorduras`, `calorias`, `imagem`, `loginid`) VALUES
(5, 'Crepioca', 'Salgado', '2 OVOs, 2 colheres (sopa) de goma de tapioca, 1 colher (sopa) e sal a gosto.', '1. Misture todos os ingredientes.\r\n2. Despeje a mistura em uma frigideira antiaderente a fogo baixo.\r\n3. Quando a parte de baixo se soltar da frigideira, vire a crepioca e deixe cozinhar o outro lado.\r\n4. Sirva em seguida.\r\n5. Utilize temperos Ã  gostoso,', 20, 11, 8, 202, '2022.10.18-21.19.58jpeg', NULL),
(6, 'Bala natural de gelatina', 'doce', '2 envelopes de Gelatina sem sabor em pÃ³ (da cor que quiser), 1 xÃ­cara (chÃ¡) de Suco de laranja sem aÃ§Ãºcar', '1. Misture os ingredientes e leve ao micro-ondas por 20 segundos. \r\n2. Coloque em forminas e leve ao congelador por 10 minutos\r\n3. estÃ¡ pronto! ', 1, 1, 0, 11, '2022.10.18-21.30.55.jpg', NULL),
(8, 'Estrogonofe de frango', 'salgado', '2 colheres (sopa) cheias de Ketchup, 2 unidades pequenas de Cebola, 1 lata de Creme de leite light, 1 colher (sopa) rasa de Molho de mostarda, 100 gramas de Peito de frango sem pele cru,1 pitada de Pimenta-do-reino em pÃ³ refinado Ã  gosto, 200 gramas de ', '1. Em uma frigideira, derreta 1 colher (sopa) da manteiga e doure o frango. Retire o frango e coloque a cebola.\r\n2. Doure a cebola, junte o frango, tempere com o sal e a pimenta.\r\n3. Junte o champignon, tampe a frigideira e deixe cozinhar por alguns minut', 4, 22, 9, 151, '2022.10.18-21.42.58.jpg', NULL),
(9, 'Fondue morango light', 'Doce', '8 envelopes de AdoÃ§ante em pÃ³, 2 unidades pequenas de Laranja, 8 unidades de Sumo de limÃ£o, 1 unidade mÃ©dia de MaÃ§Ã£ vermelha e 250 gramas de Morango', '1. Bata o suco das duas laranjas, os morangos, a maÃ§a, o adoÃ§ante e o sumo de limÃ£o no liquidificador atÃ© formar um purÃª. \r\n2. Leve ao fogo e deixe ferver por 30 minutos. \r\n3. Coloque a mistura na panela de fondue. Se achar necessÃ¡rio aumente a quantidade de limÃ£o (sumo).\r\n\r\nAcompanhamento: maÃ§Ã£, laranja, tangerina, banana, pÃªra, morango, abacaxi e uva fatiados.', 13, 1, 0, 53, '2022.10.19-14.23.39.jpg', NULL),
(10, 'Ratatouille', 'SALGADO', '1 unidade mÃ©dia de Abobrinha crua, 2 colheres (sopa) de Azeite de oliva extravirgem, 1 unidade de Berinjela crua, 1 unidade mÃ©dia de Cebola, 2 colheres (sopa) de Cheiro verde, 1 pitada de Pimenta-do-reino em pÃ³, 1 unidade mÃ©dia de PimentÃ£o verde cru,', '1. Pique a abobrinha, berinjela, tomate, cebola, pimentÃ£o verde e vermelho em rodelas.\r\n2. Disponha em uma travessa, intercalando os legumes para levar ao forno prÃ©-aquecido.\r\n3. Acrescente os temperos e o azeite por cima e leve ao forno por 30 min ou atÃ© que os legumes estejam assados.', 8, 1, 3, 60, '2022.10.19-18.47.57.jpg', NULL),
(11, 'Salada russa', 'salgado', '1 unidade pequena de Cenoura crua, 3 unidades de Palmito pupunha em conserva, 1 unidade grande de Tomate, 0,5 unidades mÃ©dias de Alface crespa, 0,5 unidades mÃ©dias de Alface roxa, 4 colheres (sopa) de Queijo parmesÃ£o ralado, 6 fatias de Peito de peru d', '1. Pique o tomate e o palmito em cubos, e rale a cenoura.\r\n2. Em uma tigela distribua as folhas de alface e adicione os legumes picados.\r\n3. Acrescente o peito de peru picado, o queijo ralado, a cebolinha, a maionese e o sal.\r\n4. Misture bem.\r\n5. Sirva.', 7, 10, 4, 97, '2022.10.19-18.58.05.jpg', NULL),
(12, 'PÃ£o de alho', 'salgado', '4 dentes de Alho cru, 2 pitadas de Sal refinado, 1, colher (chÃ¡) de OrÃ©gano seco, 1 colher (sopa) de Molho de alho, 3 unidades de PÃ£o francÃªs e 1 colher (sopa) de Azeite de oliva extravirgem.', '1. Esprema o alho e misture com o sal, orÃ©gano, molho de alho e azeite, formando uma pasta.\r\n2. Corte os pÃ£es em fatias grossas.\r\n3. Passe a pasta de alho sobre cada fatia de pÃ£o.\r\n4. Leve para assar em forno prÃ© aquecido ou em churrasqueira, atÃ© dourar.\r\n5. Sirva em seguida.', 8, 1, 1, 47, '2022.10.19-19.03.59.jpg', NULL),
(13, 'Panqueca de iogurte com morango', 'doce', '0,5 xÃ­caras (chÃ¡) de Aveia em flocos, 0,5 colheres (chÃ¡) de Fermento em pÃ³ quÃ­mico, 1 unidade de Iogurte grego sabor baunilha, 0,5 unidades mÃ©dias de Banana prata, 0,5 colheres (chÃ¡) de EssÃªncia de baunilha, 0,5 xÃ­caras (chÃ¡) de Morango e 1 unid', '1. Coloque todos os ingredientes, menos o fermento e o morango, no liquidificador. Bata atÃ© ficar homogÃªneo.\r\n2. Adicione o fermento e misture com uma colher.\r\n3. Coloque uma concha da massa em uma frigideira antiaderente e coloque alguns pedaÃ§os de morango por cima.\r\n4. Asse atÃ© formar bolhas e vire. Doure dos dois lados.\r\nEstÃ¡ pronto!', 17, 6, 4, 127, '2022.10.19-19.29.36.jpg', NULL),
(14, 'Bolo de maÃ§Ã£ light', 'doce', '1,0 xÃ­cara (chÃ¡) de Farelo de aveia, 1,0 colher (sopa) de Fermento em pÃ³ quÃ­mico, 2,0 unidades pequenas de MaÃ§Ã£, 1,0 unidade de Ovo de galinha cru, 1,0 unidade de Clara de ovo de galinha e 1,0 unidade pequena de Banana prata', '1. Em um recipiente, misture o farelo de aveia e o fermento.\r\n2. Reserve.\r\n3. Descasque as maÃ§Ã£s.\r\n4. No liquidificador, misture as maÃ§Ã£s, os ovos, a clara e a banana atÃ© ficar homogÃªneo.\r\n5. Misture com o farelo de aveia e o fermento.\r\n6. Decore com fatias de maÃ§Ã£.\r\n7. Despeje em uma assadeira e leve ao forno Ã  180Â° por 30 minutos.\r\n8. Salpique canela em pÃ³ a gosto.\r\nSirva.', 24, 6, 3, 97, '2022.10.19-19.43.37.jpg', NULL),
(15, 'Bolinhos de chocolate com coco', 'doce', '125,0 gramas de Coco fresco ralado, 2,0 colheres (sopa) de Cacau em pÃ³, 3,0 unidades de Clara de ovo de galinha e 1,0 colher (sopa) cheia de Mel.', '1. Misture todos os ingredientes atÃ© ficar homogÃªneo.\r\n2. FaÃ§a pequenas bolinhas.\r\n3. Leve ao forno preaquecido a 180Â° por cerca de 10 minutos.', 4, 2, 5, 73, '2022.10.19-19.54.23.jpg', NULL),
(17, 'Bolo de prestÃ­gio low carb', 'doce', '1 unidade de Ovo de galinha cru, 1 colher (sopa) de AdoÃ§ante em PÃ³ Para Forno, 1 colher (sopa) de Cacau em pÃ³, 1 colher (sopa) de Coco ralado e  1 colher (chÃ¡) de Fermento em pÃ³ quÃ­mico', '1. Misture todos os ingredientes.\r\n2. Leve ao microondas por 2 minutos.\r\n3. Sirva.', 1, 2, 3, 39, '2022.10.24-16.10.25.jpg', NULL),
(18, 'Torrada', 'sALGADO', '1 unidade de Ovo de galinha cru, 2 colheres (sopa) de Farinha de AmÃªndoa, 2 colheres (sopa) de Farinha de Coco, 1 colher (sopa) de Coco raladO, 0,5 colheres (sopa) de Ã“leo de coco extra virgem, Canela em pÃ³ Ã  gosto, 1 colher (sopa) de Cacau em pÃ³ E  1 colher (sopa) de AdoÃ§ante culinÃ¡rio em pÃ³.', '1.Misture todos os ingredientes e coloque a mistura numa assadeira forrada por papel manteiga em formato de quadrados (faÃ§a em mÃ©dia 3 unidades).\r\n2. Leve ao forno prÃ© aquecido a 200 graus por 15 minutos.\r\n3. Retire do forno e sirva!', 5, 5, 14, 179, '2022.10.24-16.14.32.jpg', NULL),
(19, 'Misto quente', 'Salgado', '1 unidade de Ovo de galinha cru, 1 colher (cafÃ©) de Fermento em pÃ³ quÃ­mico, Sal refinado Ã  gosto, Pimenta-do-reino em pÃ³ Ã  gosto, OrÃ©gano seco Ã  gosto, 2 colheres (sopa) de RequeijÃ£o cremoso e 2 fatias mÃ©dias de Queijo prato.', '1.Misture todos os ingredientes, exceto o queijo.\r\n2.Leve ao micro-ondas por 3 minutos.\r\n3.Recheie com o queijo e se quiser acrescente frango desfiado.\r\n4.Leve a uma sanduicheira para dourar.', 2, 16, 19, 246, '2022.10.24-16.17.52.jpg', NULL),
(20, 'Manjar de coco', 'Salgado', '1 pacote de Gelatina sem sabor, 1 embalagem de Gelatina preparada sabor abacaxi, 100 mililitros de Ãgua, 300 mililitros de Leite de coco, 1 caixinha de Creme de leite, 0,3 xÃ­caras (chÃ¡) de AdoÃ§ante forno e fogÃ£o, 100 gramas de Coco fresco ralado e  0,5 colheres (sopa) de Manteiga sem sal.', '1.Em um liquidificador, adicione a Ã¡gua e a gelatina sem sabor e bata a mistura atÃ© a gelatina dissolver. Adicione o creme de leite, o leite de coco, o adoÃ§ante e a essÃªncia de baunilha Ã  mistura. \r\n2.Bata novamente a mistura atÃ© homogeneizar.\r\n3.Adicione o coco ralado e bata por pouco tempo, para sobrarem pedaÃ§os Ã  mistura.\r\n4.Unte a forma de bolo com a manteiga.\r\n5.Espalhe na forma a gelatina com sabor jÃ¡ feita (ela serÃ¡ a cobertura do manjar)\r\n6.Derrame calmamente a mistura do liquidificador na forma, para nÃ£o misturar a gelatina com sabor ao creme\r\n7.Asse em banho-maria por 45 a 50 minutos, em fogo mÃ©dio (250 a 270Â°C). Retire e deixe na geladeira atÃ© a gelatina endurecer.\r\n8.Desenforme e sirva.', 13, 2, 19, 219, '2022.10.24-16.22.16.jpg', NULL),
(21, 'Bolo de caneca ', 'Doce', '2 colheres (sopa) de Creme de leite,  1 unidade de Ovo de galinha cru, 1 colher (chÃ¡) de EssÃªncia de baunilha, 1 colher (sopa) de Farinha de AmÃªndoa, 1 colher (cafÃ©) de Fermento em pÃ³ quÃ­mico e  2 colheres (chÃ¡) de Xylitol.', '1.Misture todos os ingredientes numa caneca, e vÃ¡ mexendo cada um com uma colher.\r\n2.Coloque no micro-ondas por 1 minuto e 40 segundos, potÃªncia alta. O tempo pode variar de acordo com o micro-ondas.\r\n3.Sirva em seguida.', 6, 9, 15, 199, '2022.10.24-16.25.40.jpg', NULL),
(22, 'Panqueca', 'Doce', '1 unidade de Ovo de galinha cru, Sal refinado Ã  gosto, 1 colher (sopa) de Farinha de AmÃªndoas, 50 mililitros de Leite integral e 1 colher (sopa) de Psyllium.', '1.Bata tudo com um garfo atÃ© ficar homogÃªneo.\r\n2.Asse na frigideira em fogo baixo e pronto!', 12, 9, 8, 162, '2022.10.24-16.32.43.jpg', NULL),
(23, 'Creme de AvelÃ£', 'Doce', '120 gramas de AvelÃ£, 3 colheres (sopa) de Cacau em pÃ³, 3 sachÃªs de AdoÃ§ante stÃ©via em pÃ³ e 200 gramas de Leite de AmÃªndoas.', '1. AqueÃ§a o forno a 265Â° por cerca de 15 minutos.\r\n2. Coloque as avelÃ£s em um tabuleiro e toste-as, mais ou menos, 10 minutos.\r\n3. Certifique-se de que elas estarÃ£o tostadas mesmo. Se elas nÃ£o tostarem o suficiente, nÃ£o irÃ£o moer direito e o creme ficarÃ¡ cheio de pedacinhos de avelÃ£ â€“ o que vai dar um gosto amargo ao doce. Bata-as junto com o cacau, a stÃ©via e o leite por 5 minutos.\r\n4. Mexa de vez em quando.\r\n5. Reserve na geladeira por aproximadamente 2 horas e sirva!', 4, 2, 7, 88, '2022.10.24-16.39.53.jpg', NULL),
(24, 'PÃ£o de forma Low Carb com parmesÃ£o', 'Salgado', '150 gramas de Farinha de AmÃªndoa, 3 unidades de Ovo de galinha cru, 50 gramas de Queijo parmesÃ£o ralado faixa azul, 3 colheres (sopa) de Ãgua, 3 colheres (sopa) de Nata de leite e  1 colher (sopa) de Fermento em pÃ³ quÃ­mico.', '1. Bata os ingredientes com exceÃ§Ã£o do fermento em um liquidificador.\r\n2. Acrescente o fermento e bata para incorporar.\r\n3. Disponha a mistura em uma forma retangular, no formato de bolo inglÃªs. \r\n4. Asse em forno a 200 graus, por 30 minutos ou atÃ© dourar.', 3, 5, 9, 117, '2022.10.24-16.44.01.jpg', NULL),
(25, 'Arroz com legumes de micro-ondas', 'Salgado', '2 xÃ­caras (chÃ¡) de Ãgua, Sal refinado Ã  gosto, Pimenta-do-reino em pÃ³ Ã  gosto, 1 xÃ­cara (chÃ¡) de Arroz integral cru, 100 gramas de Queijo MuÃ§arela Light e 0,5 latas de Seleta de legumes.', '1. Em um recipiente prÃ³prio para micro-ondas, coloque o arroz, a Ã¡gua, sal e pimenta do reino a gosto.\r\n2. Logo apÃ³s leve ao micro-ondas em potÃªncia alta por 9 minutos.\r\n3. Retire o recipiente e adicione a seleta de legumes e a mussarela cortada em cubos pequenos.\r\n4. Retorne ao micro-ondas por mais 3 minutos.\r\n5. Sirva em seguida.', 31, 9, 4, 201, '2022.10.24-16.48.01.jpg', NULL),
(26, 'Carne moÃ­da prÃ¡tica', 'Salgado', '200 gramas de Carne bovina patinho cru sem gordura, 2 colheres (sopa) picadas de Cebola, 1 dente de Alho cru, Sal refinado Ã  gosto e Pimenta-do-reino em pÃ³ Ã  gosto.', '1. Misture bem todos os ingredientes.\r\n2. Coloque em um refratÃ¡rio, cubra com filme plÃ¡stico (faÃ§a alguns furinhos para o vapor sair) e leve ao micro-ondas por 8 minutos em potÃªncia alta.\r\n3. Sirva em seguida.', 1, 11, 2, 70, '2022.10.24-16.50.52.jpg', NULL),
(27, 'Batata recheada no micro-ondas', 'Salgado', '1 fatia fina de Queijo muÃ§arela light,  1 pitada de Sal refinado, 1 unidade mÃ©dia de Batata inglesa crua, 1 colher (sopa) de Salsinha e 1 colher (sobremesa) de Manteiga sem sal', '1. Com um garfo, faÃ§a diversos furos na batata.\r\n2. Coloque em um recipiente prÃ³prio para micro-ondas e deixe por 5 a 6 minutos em potÃªncia mÃ¡xima, virando a batata na metade do tempo.\r\n3. Com cuidado para nÃ£o se queimar, faÃ§a um corte na batata no sentido do comprimento, mas sem cortar a batata ao meio.\r\n4. Com um garfo, retire a polpa.\r\n5. Misture essa polpa com manteiga e sal, quase fazendo um \"purÃª\".\r\n6. Acrescente a mussarela fatiada.\r\n7. Recheie a batata com essa mistura, coloque no micro-ondas por mais 1 minuto para derreter o queijo, salpique salsinha e sirva.', 11, 6, 10, 158, '2022.10.24-16.57.23.jpg', NULL),
(30, 'Gaspacho', 'Salgado', '1 dente de Alho cru, 2 colheres (sopa) de Azeite de oliva extravirgem, 1 unidade pequena de Cebola, 1 unidade mÃ©dia de PimentÃ£o vermelho cru, 500 gramas de Tomate, 1 unidade de Sumo de limÃ£o, 1 colher (sobremesa) de PÃ¡prica picante, 1 colher (chÃ¡) de OrÃ©gano seco, Pimenta-do-reino em pÃ³ Ã  gosto, Sal refinado Ã  gosto, 1 unidade pequena de Pepino, 3 copos requeijÃ£o de Suco de tomate e 3 fatias de PÃ£o de forma integral.', '1. Bata todos os ingredientes no liquidificador atÃ© ficar cremoso.\r\n2. Coloque numa sopeira com tampa e leve Ã  geladeira por cerca de 2 horas.\r\n3. Enquanto isso, corte as fatias de pÃ£o em cubos e disponha em uma fÃ´rma.\r\n4. Tempere com um fio de azeite os cubinhos de pÃ£o.\r\n5. Leve ao forno mÃ©dio (180Â°C) atÃ© dourar.\r\n6. Sirva a sopa com os cubinhos de pÃ£o.', 9, 2, 2, 62, '2022.10.25-14.46.07.jpg', NULL),
(31, 'Salada de maionese low carb', 'Salgado', '1 unidade grande de Chuchu cru, 0,5 unidades grandes de Cenoura crua, 2 colheres (sopa) cheias de Creme de leite light, 0,5 dentes de Alho cru, Sal refinado Ã  gosto, Salsinha Ã  gosto e  2 colheres (sopa) de RequeijÃ£o cremoso', '1. Cozinhe em Ã¡gua, o chuchu e a cenoura.\r\n2. Espere esfriar e misture o restante dos ingredientes.\r\n3. Sirva gelada.', 4, 1, 2, 37, '2022.10.25-14.51.20.jpg', NULL),
(32, 'AlmÃ´ndega de micro-ondas', 'Salgado', '250 gramas de Carne bovina patinho cru sem gordura, 1 unidade de Ovo de galinha cru, 1 xÃ­cara (chÃ¡) de Molho de tomate caseiro (tomate, cebola e/ou alho), Sal refinado Ã  gosto, Pimenta-do-reino em pÃ³ Ã  gosto, 1 colher (sopa) rasa picada de Cebolinha crua, 1 colher (sopa) de Salsinha e  1 colher (sopa) de Aveia em flocos finos.', '1. Misture a carne moÃ­da, a aveia, o ovo, o sal, a pimenta-do-reino, a cebolinha e a salsinha atÃ© formar uma massa homogÃªnea.\r\n2. Com o auxÃ­lio de 2 colheres de sobremesa, molde as almÃ´ndegas, com cerca de 25g cada.\r\n3. Disponha os bolinhos em um refratÃ¡rio, cubra com filme plÃ¡stico (faÃ§a pequenos furinhos para o vapor sair) e leve ao micro-ondas em potÃªncia alta por 6 minutos.\r\n4. Acrescente o molho de tomate e volte ao micro-ondas por mais 1 minuto.\r\n5. Sirva em seguida.', 1, 6, 2, 48, '2022.10.25-14.57.27.jpg', NULL),
(33, 'Ceviche simples', 'Salgado', '250 gramas de FilÃ© de tilÃ¡pia, 2 unidades de LimÃ£o, 0,5 unidades de Cebola roxa, 2 unidades pequenas de Tomate, Pimenta dedo de moÃ§a Ã  gosto, Coentro fresco Ã  gosto, Sal refinado Ã  gosto e  Azeite de oliva extravirgem Ã  gosto.', '1. Pique a pimenta e retire as sementes\r\n2. Misture o peixe, a cebola, e a pimenta em um recipiente, acrescente o sal e misture\r\n3. Coloque o suco dos limÃµes e leve Ã  geladeira por 1 hora\r\n4. Na hora de servir acrescente o tomate, o coentro e um fio de azeite\r\n', 8, 14, 1, 87, '2022.10.25-15.00.49.jpg', NULL),
(34, 'Barra de cereal detox', 'Doce', '1,5 xÃ­caras (chÃ¡) de Aveia em flocos, 0,5 xÃ­caras (chÃ¡) de Coco fresco ralado, 0,5 xÃ­caras (chÃ¡) de Mix frutas secas, 3 colheres (sopa) de Melado de cana, 4 colheres (sopa) de Pasta integral de amendoim, 100 gramas de Castanha do parÃ¡ sem casca, 0,5 xÃ­caras (chÃ¡) de Nozes sem casca 100 gramas de Castanha de caju, 8 colheres (sopa) de Cacau nibs orgÃ¢nico, 1,5 colheres (sopa) de Semente de chia e Canela em pÃ³ Ã  gosto.', '1. Misture todos os ingredientes atÃ© formar uma massa.\r\n2. Coloque toda a massa em uma forma.\r\n3. Deixe descansar na geladeira por uns 20 minutos pra que fique mais fÃ¡cil de cortar.\r\n4. Divida em em 10 porÃ§Ãµes no formato de barra de cereal e coloque as mesmas em um recipiente para armazenar.', 25, 7, 18, 284, '2022.10.25-15.05.23.jpg', NULL),
(35, 'Sorvete de banana com cacau', 'Doce', '4 unidades mÃ©dias de Banana prata, 1 colher (sopa) de Cacau em pÃ³ MÃ£e, 1 colher (sopa) de AmÃªndoa em lÃ¢minas, 1 colher (chÃ¡) de Mel de abelha e 300 mililitros de Leite de coco de caixinha.', '1. Coloque as bananas no congelador com casca. \r\n2. Depois de congeladas retirar do congelador limpar as mesas e descascar. \r\n3. Corte a banana e coloque no liquidificador com o cacau e o leite de coco atÃ© formar uma pasta com consistÃªncia de sorvete. \r\n4. Sirva com as amÃªndoas e ou outras castanhas por cima e o mel.', 10, 1, 4, 77, '2022.10.25-15.08.32.jpg', NULL),
(36, 'PÃ£o de queijo leve', 'Salgado', '1 unidade de Ovo de galinha cru, 180 gramas de Queijo Frescal, 5 colheres (sopa) de Azeite de oliva extravirgem, 400 gramas de Polvilho doce e 1 copo de Ãgua.', '1. Reservar o polvilho.\r\n2. Bater todos os outros ingredientes no liquidificador.\r\n3. despejar a mistura em um recipiente e misturar o polvilho.\r\n4. formar bolinhas com colher, colocar em forma untada com azeite e assar em forno mÃ©dio atÃ© dourar. \r\n5. Pode congelar cru e levar ao forno ainda congelado', 12, 2, 3, 77, '2022.10.25-15.11.33.jpg', NULL),
(37, 'Coxinha1', 'Salgado', '1 unidade pequena de Cebola, 100 gramas de Frango peito cru, 4 cubos de Caldo de galinha Knorr, 3 unidades mÃ©dias de Batata inglesa crua, 3 colheres (sopa) de Ã“leo de girassol, 0,5 xÃ­caras (chÃ¡) de Salsa, 150 gramas de Margarina com sal light, 5 xÃ­caras (chÃ¡) de Farinha de trigo comum, 4 unidades mÃ©dias de Ovo de galinha cru e 100 gramas de Farinha de rosca.', 'RECHEIO: \r\n1. COLOQUE EM UMA PANELA SEIS XÃCARAS (CHÃ) DE ÃGUA, TRÃŠS TABLETES DE CALDO DE GALINHA , O PEITO DE FRANGO, AS BATATAS E LEVE AO FOGO,MEXENDO ATÃ‰ OS TABLETES SE DESMANCHAREM. \r\n2. DEIXE COZINHAR ATÃ‰ FICAR MACIO. \r\n3. ESPREMA AS BATATAS AINDA QUENTES E RESERVE-AS. \r\n4. RESERVE TAMBÃ‰M O CALDO DO COZIMENTO.\r\n5. DESFIE O FRANGO. EM UMA PANELA, AQUEÃ‡A O Ã“LEO E DOURE LEVEMENTE A CEBOLA JUNTE O FRANGO DESFIADO, O TABLETE DE CALDO RESTANTE E DEIXE REFOGAR BEM, MEXENDO SEMPRE, ATÃ‰ FICAR BEM SEQUINHO. \r\n6. ACRESCENTE A SALSA, MISTURE E DEIXE ESFRIAR.\r\n\r\nMASSA: \r\n1. EM UMA PANELA GRANDE, COLOQUE AS BATATAS ESPREMIDAS O CALDO RESERVADO (DEVE DAR 5 XÃCARAS DE CHÃ; CASO FALTE, COMPLETE COM ÃGUA), JUNTE A MARGARINA DEIXE LEVANTAR FERVURA. \r\n2. POLVILHE A FARINHA DE TRIGO, MEXENDO SEMPRE, ATÃ‰ OBTER UMA MASSA HOMOGÃŠNEA. \r\n3. COZINHE POR MAIS UNS MINUTOS, MEXENDO FORTEMENTE. \r\n4. DESPEJE SOBRE UMA SUPERFÃCIE E SOVE A MASSA DELICADAMENTE ATÃ‰ ESFRIAR.\r\n\r\nMONTAGEM: \r\n1. ABRA PEQUENAS PORÃ‡Ã•ES DA MASSA NA PALMA DA MÃƒO E RECHEIE. \r\n2. MODELE COMO COXINHAS, PASSE-AS PELA FARINHA DE ROSCA, PELOS OVOS BATIDOS E NOVAMENTE PELA FARINHA DE ROSCA. \r\n3. FRITE-AS EM Ã“LEO QUENTE, ESCORRA-AS EM PAPEL TOALHA.', 13, 8, 4, 120, '2022.10.25-15.19.44.jpg', NULL),
(38, 'Suco detox de gengibre, cardamomo e hibisco', 'Bebida', '6 gramas de Gengibre, 8 gramas de Cardamomo, 1 unidade de Cravo da Ãndia, 1 colher (sopa) de Folhas secas de hibisco, 1 xÃ­cara (chÃ¡) de Ãgua e  1 unidade pequena de MaÃ§Ã£ fuji.', '1. FaÃ§a a infusÃ£o das folhas de hibisco na Ã¡gua e reserve.\r\n2. Em seguida coe e bata o chÃ¡ no liquidificador com os outros ingredientes.', 16, 1, 1, 60, '2022.10.25-15.23.30.jpg', NULL),
(39, 'Chocolate quente light', 'Bebida', '3 colheres (sopa) de Achocolatado em pÃ³ light Nescau, Canela em pau Ã  gosto, 1 colher (sopa) cheia de Amido de milho, 2 colheres (sobremesa) cheias de Creme de leite light, 1 gota de AdoÃ§ante lÃ­quido e  2 copos de Leite desnatado.', '1. Misture o leite ainda frio com o amido de milho.\r\n2. Leve ao fogo, adicione o achocolatado e a canela.\r\n3. Ao ferver, desligue e deixe esfriar por 2 minutos.\r\n4. Acrescente o creme de leite e se necessÃ¡rio adoce com o adoÃ§ante.\r\n5. Sirva.', 25, 7, 2, 157, '2022.10.25-15.28.17.jpg', NULL),
(40, 'Suco antioxidante', 'Bebida', '1 unidade pequena de Cenoura crua, 1 copo americano de Suco de laranja sem aÃ§Ãºcar e 1 folha grande de Couve manteiga crua.', '1. Bata o suco de laranja com a cenoura e a couve no liquidificador. \r\n2. coe e sirva em seguida.', 18, 2, 1, 78, '2022.10.25-15.30.46.jpg', NULL),
(41, 'Salada de frutas com cobertura de iogurte', 'Doce', '2 fatias mÃ©dias de Abacaxi, 1 unidade mÃ©dia de Banana nanica, 1 unidade de Iogurte natural desnatado, 0,5 unidades mÃ©dias de MamÃ£o papaia, 1 fatia grossa de MelÃ£o, 1 unidade mÃ©dia de Mexerica, 12 unidades mÃ©dias de Morango, 1 unidade mÃ©dia de Pera willians, 1 cacho mÃ©dio de Uva rubi, 1 unidade mÃ©dia de MaÃ§Ã£ fuji, 2 colheres (sopa) de Flocos de cereais e 1 colher (sopa) de Mel de abelha.', '1. Pique as frutas em uma tigela grande e misture.\r\n2. Distribua o mix de frutas em taÃ§as individuais, reserve.\r\n3. Misture o iogurte desnatado com o mel.\r\n4. Coloque cerca de 1 colher de sopa do iogurte sobre cada taÃ§a.\r\n5. Salpique flocos de cereais integrais e sirva.', 35, 3, 1, 147, '2022.10.25-15.34.15.jpg', NULL),
(42, 'PurÃª de carÃ¡ com espinafre', 'Salgado', '0,5 unidades pequenas de Cebola, 1 xÃ­cara (chÃ¡) de Espinafre cru, 12 colheres (arroz) rasas de CarÃ¡ cozido, 1,5 xÃ­caras (chÃ¡) de Leite desnatado, 1 colher (cafÃ©) de Sal refinado e 1 colher (sopa) de Manteiga com sal.', '1. Em uma panela, derreta a manteiga e refogue com a cebola ralada atÃ© murchar. \r\n2. Junte as folhas de espinafre e refogue por mais 3 minutos.\r\n3. Adicione o carÃ¡ amassado e mexa. \r\n4. Junte o leite, aos poucos, mexendo atÃ© que todos os ingredientes fiquem integrados.\r\n5. Tempere com o sal e sirva.', 9, 2, 1, 51, '2022.10.25-15.37.14.jpg', NULL),
(43, 'Bauru', 'Salgado', '1 ovo;\r\n2 colheres (sopa) de requeijÃ£o tradicional;\r\n1 colher (chÃ¡) de fermento em pÃ³;\r\n1 fatia de queijo muÃ§arela;\r\n1 fatia de peito de peru;\r\n2 fatias mÃ©dias de tomate;\r\n1 folha de alface;\r\n1 pitada de orÃ©gano;', '1- Para fazer o â€œpÃ£oâ€, misture bem o ovo e duas colheres de requeijÃ£o, depois acrescente o fermento em pÃ³ Ã  mistura.\r\n\r\n2- Unte com azeite um recipiente quadrado, coloque a mistura e leve ao micro-ondas por cerca de 2 minutos e meio. \r\n\r\n3- Retire do micro-ondas, desenforme, corte pela metade e recheie com a muÃ§arela, o peito de peru, a folha de alface, o tomate e o orÃ©gano ou o recheio que preferir. \r\n\r\n4- Depois, coloque na sanduicheira para finalizar seu lanche', 7, 28, 31, 430, '2022.11.16-12.41.50.jpg', NULL),
(44, 'Massa de pizza de frigideira', 'Salgado', '3 ovos;\r\n300g de peito de frango desfiado cozido;\r\n1 colher (sopa) azeite de oliva;\r\nSal Ã  gosto;\r\nPimenta-do-reino Ã  gosto.', '1- Misture todos os ingredientes e bata no liquidificador. \r\n2- Espalhe a massa em uma forma de pizza e asse por cerca de 10 minutos em forno alto. \r\n3- Vire a massa e asse do outro lado. \r\n4- Depois, recheie como preferir.', 3, 87, 34, 663, '2022.11.16-12.44.27.jpg', NULL),
(45, 'Tartar de SalmÃ£o com Guacamole', 'Salgado', 'Ingredientes do Tartar de SalmÃ£o:\r\n300g de salmÃ£o fresco;\r\n2 colheres (sopa) de azeite extra virgem;\r\n1 colher (chÃ¡) de mostarda Dijon;\r\nSuco de 1 limÃ£o;\r\nPimenta-dedo-de-moÃ§a Ã  gosto;\r\nSal e pimenta-do-reino Ã  gosto.\r\n\r\nIngredientes do Guacamole:\r\n50g de polpa de abacate maduro e firme;\r\n20g de cebola roxa picada;\r\n10g de tomate sem pele e sem sementes;\r\nPimenta-dedo-de-moÃ§a Ã  gosto;\r\nSuco de 1 limÃ£o;\r\nFolhas de coentro fresco Ã  gosto;\r\nSal e pimenta-do-reino Ã  gosto.\r\n', 'Modo de preparo do Tartar de SalmÃ£o:\r\n1- Corte o salmÃ£o em cubinhos pequenos e a pimenta dedo-de-moÃ§a em pedacinhos bem pequenos. \r\n2- Misture com os outros ingredientes e reserve.\r\n\r\nModo de preparo do Guacamole:\r\n1- Pique o abacate, a cebola roxa e o tomate em cubos. \r\n2- Coloque a pimenta cortada em pedaÃ§os bem pequenos, o coentro e misture delicadamente todos os ingredientes, para nÃ£o desmanchar todo o abacate.\r\n\r\nMontagem do Tartar de SalmÃ£o:\r\n1- Coloque o tartar em um recipiente (taÃ§a) e coloque um pouco da guacamole por cima. \r\n2- Sirva frio.', 5, 73, 71, 981, '2022.11.16-12.51.39.png', NULL),
(46, 'Lasanha de Abobrinha ', 'Salgado', '500 gramas de carne moÃ­da crua; \r\n1 unidade grande de cebola (150g); \r\n1 xÃ­cara de chÃ¡, tomate cereja picado (132G); \r\n1 lata de tomate, vermelho, maduro, lata, inteiro, sem sal (190g); \r\n400 gramas de queijo muÃ§arela light fatiado;\r\n50 gramas de queijo parmesÃ£o;\r\n1 unidade de suco de limÃ£o-galego, cru (44g);\r\n3 abobrinhas italiana crua em fatias de 1/2 cm (580g);', '1- Refogue bem a carne com a cebola e tempere a gosto;\r\n2- Adicione os tomates e a lata de tomate;\r\n3- Deixe cozinhar em fogo baixo atÃ© reduzir um pouco;\r\n4- Coloque as abobrinhas fatiadas em um recipiente com suco de limÃ£o;\r\n5- Coloque Ã¡gua para ferver com um pouco de sal;\r\n6- Cozinhe as abobrinhas por 2 minutos, depois deixe-as em Ã¡gua gelada;\r\n\r\nMontagem: \r\n1- Intercale camadas de abobrinhas, o molho de carne e a muÃ§arela; \r\n2- Na Ãºltima camada polvilhe o parmesÃ£o;\r\n3- Asse em forno aquecido a 180Âº por 20 minutos e sirva.', 4, 16, 9, 168, '2022.11.16-13.27.38.jpg', NULL),
(47, 'Arroz de couve flor e cenoura', 'Sagado', '1 unidade de couve-flor crua (300 g);\r\n\r\n1 unidade mÃ©dia de cenoura crua (120 g);\r\n\r\n1 unidade pequena de cebola ralada (30 g);\r\n\r\n1 dente de alho, cru (3g);\r\n\r\n22 gramas de limÃ£o (sumo de meio limÃ£o);\r\n\r\n3 colheres de sopa de azeite de oliva extra virgem (24 g);\r\n', '1.Comece lavando os floretes de couve-flor em Ã¡gua corrente, em seguida seque bem e passe no processador ou ralo\r\n2.Junte o sumo do limÃ£o e sal a gosto\r\n3.Numa frigideira antiaderente em fogo mÃ©dio coloque o azeite a cebola refogue um minuto e junte o alho, deixe mais um minuto e\r\ncoloque a cenoura ralada refoque por mais um minuto\r\n4.Junte o couve-flor e refoque bem, desligue o fogo e acerte o sal.', 28, 8, 25, 337, '2022.11.16-15.03.58jpeg', NULL),
(48, 'esfirra', 'salgado', '1Âº Misture todos os ingredientes, deixando o sal e o fermento por Ãºltimo o sal e o fermento.\r\n\r\n2Âº Separe a maÃ§a em pequenas quantidades e faÃ§a o formato das esfirras em uma forma com papel manteiga ou untada com\r\nazeite.\r\n\r\n3Âº Asse no forno a 200 graus por 15 minutos\r\n\r\n4Âº Coloque o recheio de sua preferÃªncia e volte para o forno por mais 5 minutos.\r\n\r\n5Âº SugestÃ£o de recheio [queijo , frango desfiado, carne de sol, brÃ³colis com queijo, champinhom]\r\n', ' 6 colheres de sopa cheias de farinha de aveia (108g);\r\n 1 colher de sopa rasa de creme de leite (15g);\r\n 1 unidade de ovo de galinha (45g);\r\n 1 colher de sopa de fermento quÃ­mico em pÃ³ (10 g);\r\n 50 gramas de mussarela e 1/2 colher de chÃ¡ de sal dietÃ©tico;', 32, 14, 12, 283, '2022.11.16-15.07.59jpeg', NULL),
(49, 'choconana', 'doce', '', '', 16, 13, 16, 0, '2022.11.16-15.23.15', NULL),
(50, 'choconana', 'doce', '2 ovos;\r\n30 gramas de farinha de tapioca;\r\n2 colheres de sopa (30g) de aveia em flocos;\r\n1 banana;\r\n20 gramas(1 fatia) de queijo minas;\r\n1 tablete pequeno de chocolate meio amargo;', '1Âº\r\nBata o ovo com a farinha da tapioca e a banana (caso deseje acrescentar adoÃ§ante ou canela - Ã  gosto). Leve ao fogo em uma frigideira anti-aderente atÃ© dourar dos dois lados.\r\n2Âº\r\nQuando estiver pronto acrescente o chocolate em forma de raspas sobre a mesma e leve ao fogo alguns segundos atÃ© derreter. Prontinho. Bom apetite!', 16, 13, 14, 238, '2022.11.16-15.30.20jpeg', NULL),
(51, 'TRUFA DE CHOCOLATE', 'doce', '60 gramas de chocolate meio amargo;\r\n60 gramas de creme de leite;\r\n1 colher de chÃ¡ rasa de manteiga sem sal (4 g)ou1 colher de chÃ¡ de Ã³leo de coco (5 g);\r\n2 colheres de sopa de cacau em pÃ³ (11 g);\r\n1 colher de chÃ¡ de licor (5 ml) - opcional;\r\n', '1Âº\r\nRale o chocolate meio amargo em um recipiente e reserve.\r\n2Âº\r\nEm uma panela, aqueÃ§a o creme de leite atÃ© que engrosse como um molho. Desligue o fogo, e junte o chocolate ralado e mexa atÃ© derreter.\r\n3Âº\r\nJunte a manteiga e mexa atÃ© estar homogÃªneo. Se quiser, junte o licor e mexa bem.\r\n4Âº\r\nTransfira para um recipiente de vidro e cubra com filme plÃ¡stico para que nÃ£o seja formada uma pelÃ­cula na superfÃ­cie. Deixe na geladeira atÃ© esfriar.\r\n5Âº\r\nRetire da geladeira e com ajuda de duas colheres pequenas modele as trufas no formato que desejar. Passe pelo cacau em pÃ³ para que fiquem cobertas.', 34, 4, 28, 351, '2022.11.16-15.35.42jpeg', NULL),
(52, 'CUPCAKE DE CHOCOLATE', 'doce', '175 gramas de chocolate meio amargo;\r\n11 colheres de chÃ¡ cheias de manteiga sem sal em temperatura ambiente (amolecida) (88 g);\r\n4 ovos (120 g);\r\n2 colheres de sopa rasas de aÃ§Ãºcar mascavo, de coco ou refinado (22 g);\r\n1 gema (17 g);\r\n', '1Âº\r\nSepare as claras dos ovos. Em uma batedeira, bata as claras com o aÃ§Ãºcar atÃ© o ponto de merengue mole (nÃ£o deixe endurecer). Reserve.\r\n2Âº\r\nÃ€ parte, retire a pele das gemas de ovo e bata com um fouet por cerca de 3 minutos. Despeje sobre o merengue e misture delicadamente com o auxÃ­lio de uma espÃ¡tula. Reserve.\r\n3Âº\r\nRale o chocolate meio amargo e derreta-o em banho-maria. Em seguida, incorpore a manteiga.\r\n4Âº\r\nAdicione o chocolate derretido ao merengue.\r\n5Âº\r\nDistribua em forminhas pequenas e asse em forno prÃ©-aquecido a 200ÂºC por 12 minutos. Deixe esfriar para desenformar.\r\n', 31, 6, 34, 431, '2022.11.16-15.42.07jpeg', NULL),
(53, 'PASTA DE CASTANHA DE CAJU', 'doce', '500 gramas de castanha de caju', '1Âº\r\nUse a castanha de caju jÃ¡ torrada, preferencialmente sem. Caso tenha a castanha de caju crua, torre-as em uma frigideira ou no forno em baixa temperatura (150 - 180 Â°C) atÃ© que fiquem douradas.\r\n2Âº\r\nTriture as castanhas no liquidificador atÃ© que seja formada uma massa nÃ£o homogÃªnea e empelotada (os liquidificadores de baixa potÃªncia precisam de descanso para nÃ£o aquecerem, desligue um pouco e espere o motor esfriar para continuar).\r\n3Âº\r\nContinue batendo atÃ© obter uma pasta lisa. Sirva ou guarde em um pote bem fechado.', 33, 15, 46, 574, '2022.11.16-15.47.30jpeg', NULL),
(54, 'PICOLÃ‰ DE ABACAXI', 'doce', '1Âº\r\nBata todos os ingredientes, coloque as folhas de hortelÃ£ e derrame a mistura em forminhas para picolÃ©.\r\n2Âº\r\nDerrame o suco em forminhas de picolÃ©\r\n3Âº\r\nLeve ao congelador por pelo menos 3 horas\r\n', '4 fatias mÃ©dias de abacaxi cru (300 g);\r\n250 gramas de Ã¡gua mineral natural;\r\n10 folhas de hortelÃ£, fresco (2 g);\r\n1 colher de chÃ¡ de gengibre, cru (2 g);\r\n', 7, 0, 0, 27, '2022.11.16-15.54.39jpeg', NULL),
(57, 'QUEIJO COTTAGE CASEIRO', 'Salgado', '1 litro de leite integral;\r\n90 ml de suco de limÃ£o;', '1Âº\r\nEm uma panela, aqueÃ§a leite atÃ© 90 ÂºC (ficarÃ¡ espumoso e cheio de bolhas), se puder use um termÃ´metro. Adicione o suco de limÃ£o e baixe o fogo, aguarde 5 minutos.\r\n2Âº\r\nDeixe esfriar, retire o coÃ¡gulo com uma peneira e escorra em um pano de prato limpo por cerca de 1 hora. Guarde na geladeira ainda envolto com o pano por mais 4 horas, para drenar o restante do soro. Depois de pronto, tempere com sal a gosto.\r\n', 5, 3, 3, 57, '2022.11.16-16.03.03jpeg', NULL),
(58, 'BISCOITO DE GERGELIM E BATATA DOCE', 'doce', '135 gramas de batata doce crua;\r\n100 gramas de gergelim semente;', '1Âº\r\nCozinhe a batata doce sem casca e cozinhe por 25 min ou atÃ© ficar macia;\r\n2Âº\r\nAmasse atÃ© formar um purÃª e acrescente o gergelim e temperos a gosto;\r\n3Âº\r\nMeÃ§a uma colher de sopa a cada bolinha e leve pra assar no forno a 200Âº por 20 minutos.\r\n', 25, 10, 22, 316, '2022.11.16-16.08.13jpeg', NULL),
(59, 'SMOOTHIE DE FRUTAS VERMELHAS', 'doce', '100 ml de iogurte natural bem gelado;\r\n2 unidades de banana madura congelada (130 g);\r\n5 unidades mÃ©dias de morango (60 g);\r\n100 gramas de frutas vermelhas congeladas (mirtilo, amora, framboesa);\r\n', '1Âº\r\nEm um liquidificador ou processador, bata as frutas vermelhas com a banana. Em seguida adicione o iogurte e bata atÃ© ter uma mistura homogÃªnea.\r\n', 14, 3, 0, 66, '2022.11.16-16.11.44jpeg', NULL),
(60, 'CANJA DE GALINHA', 'salgado', '2 unidades grandes de peito de frango em pedaÃ§os (540 g);\r\n3 unidades pequenas de cenoura cortada em rodelas (165 g);\r\n4 colheres de sopa de alho-porÃ³ em fatias (80 g);\r\n1 unidade mÃ©dia de batata inglesa em pedaÃ§os (140 g);\r\n1 concha mÃ©dia cheia de arroz integral cru (117 g);\r\n1 unidade mÃ©dia de cebola crua ralada (70 g);\r\n4 dentes de alho esmagados (12 g);\r\n1 xÃ­cara de chÃ¡ de salsinha picada (60 g);\r\n1 colher de sopa de azeite de oliva extra virgem (8 g);\r\n1 colher de chÃ¡ de sal (6 g);', '1Âº\r\nNuma panela alta, coloque o azeite e o alho esmagado e deixe dourar. Adicione a cebola e refogue atÃ© que ela fique translÃºcida. Em seguida adicione o alho-porÃ³ ao refogado.\r\n2Âº\r\nÃ€ parte, tempere os pedaÃ§os de frango com sal e pimenta do reino. Coloque na panela junto com o alho, a cebola e o alho-porÃ³ e deixe dourar. Retire o frango e reserve num recipiente Ã  parte, bem fechado.\r\n3Âº\r\nNa panela, refogue o arroz e adicione 2 litros de Ã¡gua. Coloque as batatas e cozinhe atÃ© estarem al dente. Em seguida adicione as cenouras. Se preferir, cozinhe separadamente para nÃ£o passar do ponto.\r\n4Âº\r\nCom o arroz, a batata e a cenoura jÃ¡ cozidos, junte o frango e a salsinha. Prove, e ajuste o sal e pimenta se necessÃ¡rio.\r\n', 12, 15, 3, 139, '2022.11.16-16.19.10jpeg', NULL),
(61, 'FONDUE DE CHOCOLATE', 'doce', '1Âº\r\nEm um recipiente fundo, rale o chocolate com o auxÃ­lio de um ralador de metal e depois reserve.\r\n2Âº\r\nEm uma panela, ferva o creme de leite e deixe-o cozinhar por cerca de 5 minutos ou atÃ© que fique mais encorpado.\r\n3Âº\r\nDesligue o fogo e adicione o chocolate aos poucos atÃ© que a mistura fique homogÃªnea.\r\n4Âº\r\nMantenha a mistura aquecida em um acessÃ³rio especÃ­fico para fondue.\r\n5Âº\r\nSirva com os morangos.', '200 gramas de creme de leite;\r\n200 gramas de chocolate meio amargo;\r\n30 unidades mÃ©dias de morango (360 g);', 21, 2, 14, 198, '2022.11.16-16.22.44jpeg', NULL),
(62, 'CROSTINI Ã€ NAPOLITANA', 'salgado', '4 fatias grandes de pÃ£o (italiano ou ciabatta) (116 g);\r\n2 unidades de tomate italiano (124 g);\r\n175 gramas de mussarela de bÃºfala;\r\n4 unidades de filÃ©s de aliche (16 g);\r\n3 colheres de sopa de azeite de oliva extra virgem (24 ml);\r\n6 unidades mÃ©dias de azeitona preta em conserva (18 g);\r\n1 colher de chÃ¡ de orÃ©gano (1 g);\r\n1 pitada de pimenta do reino;', ' 1Âº\r\nCORTE AS FATIAS DE PÃƒO AO MEIO E DISTRIBUA EM UMA ASSADEIRA UNTADA COM AZEITE. FATIE A MUSSARELA E DISTRIBUA SOBRE AS FATIAS DE PÃƒO.\r\n2Âº\r\nEM UMA PANELA COM ÃGUA FERVENTE, ESCALDE OS TOMATES POR DOIS MINUTOS. ESCORRA, RETIRE A PELE, CORTE AO MEIO E RETIRE AS SEMENTES. CORTE EM TRIÃ‚NGULOS OU CUBOS E DISTRIBUA SOBRE AS FATIAS DE PÃƒO.\r\n3Âº\r\nCORTE AS AZEITONAS AO MEIO, NO SENTIDO DO COMPRIMENTO (RETIRE O CAROÃ‡O, SE HOUVER), E DISTRIBUA SOBRE AS FATIAS DE PÃƒO.\r\n4Âº\r\nPARA FINALIZAR A MONTAGEM, COLOQUE O ALICHE EM FATIAS BEM FININHAS, TEMPERE COM PIMENTA DO REINO E REGUE COM AZEITE.\r\n5Âº\r\nAQUEÃ‡A O FORNO A 200 ÂºC POR QUINZE MINUTOS. COLOQUE A ASSADEIRA COM OS CROSTINIS E DEIXE ASSAR POR 8 MINUTOS, OU ATÃ‰ O PÃƒO ESTAR DOURADO E O QUEIJO DERRETIDO. RETIRE DO FORNO, DISTRIBUA AS FOLHAS DE ORÃ‰GANO FRESCAS E SIRVA.', 14, 12, 16, 245, '2022.11.16-16.27.05jpeg', NULL),
(63, 'SANDUÃCHE NATURAL DE FRANGO', 'salgado', '2 fatias de pÃ£o integral light (50 g)ou1 unidade pequena de pÃ£o, sÃ­rio, trigo integral (28 g);\r\n2 colheres de sopa cheias, desfiado de frango cozido (40 g);\r\n1 colher de sopa cheia de requeijÃ£o light (30 g)ou 1 fatia de queijo ricota (50 g);\r\n2 folhas pequenas de alface, crespa, crua (10 g);\r\n2 fatias mÃ©dias de tomate com semente cru (30 g);\r\n1 colher de sopa cheia, ralada de cenoura crua (12 g);', '1Âº\r\nMisture os ingredientes do recheio (menos a alface e o tomate)\r\n2Âº\r\nRecheie o pÃ£o com ricota ou requeijÃ£o light, acrescente frango desfiado e cenoura ralada\r\n3Âº\r\nColoque a alface e o tomate.\r\n4Âº\r\nBom apetite!', 13, 12, 6, 153, '2022.11.16-16.29.24jpeg', NULL),
(64, 'BOLINHO DE BACALHAU', 'salgado', '2 postas grandes de bacalhau (440 g);\r\n3 unidades mÃ©dias de batata (420 g);\r\n1 unidade grande de cebola crua (150 g);\r\n4 colheres de sopa de salsinha (15 g);\r\n2 unidades de ovo de galinha (156 g);\r\n1/2 colher de chÃ¡ de pimenta do reino (1 g);', '1Âº\r\nDessalga: Em um recipiente grande, coloque o bacalhau e cubra com Ã¡gua filtrada e coloque na geladeira. Escorra a Ã¡gua e cubra o bacalhau com mais Ã¡gua filtrada. Repita este processo para dessalgar o bacalhau por 48 horas. Despreze a Ã¡gua do bacalhau.\r\n2Âº\r\nEm uma panela cozinhe o bacalhau por 10 minutos. Escorra e reserve. Remova a pele e as espinhas, e entÃ£o, desfie o peixe.\r\n3Âº\r\nEm uma bancada, abra um pano de prato limpo e coloque o bacalhau no centro do pano, feche como uma trouxa e aperte bem atÃ© o bacalhau estar com textura de \"fios de cabelo embolados\". Reserve.\r\n4Âº\r\nEm uma panela de pressÃ£o coloque as batatas e cubra com Ã¡gua. Tampe, espere ferver, e cozinhe na pressÃ£o por 20 minutos ou atÃ© as batatas estarem macias. Desligue, e espere a pressÃ£o ser liberada da panela. Abra a tampa e escorra a Ã¡gua. Amasse bem as batatas.\r\n5Âº\r\nEm um recipiente grande, misture a batata amassada, o bacalhau desfiado, a cebola ralada, a salsinha bem picadinha e tempere com a pimenta do reino. Adicione aos poucos os ovos batidos, misturando bem, atÃ© conseguir formar bolinhas bem lisinhas. Ajuste o sal.\r\n6Âº\r\nForme os bolinhos no formato desejado, pincele um pouco de azeite e frite em temperatura mÃ©dia-alta (160 a 180ÂºC) atÃ© dourarem.Para uma versÃ£o com menor teor de gorduras utilize uma fritadeira a ar (Air Fryer).', 7, 12, 2, 91, '2022.11.16-16.31.54jpeg', NULL),
(65, 'PAELLA VALENCIANA', 'Salgado', '1 colher de chÃ¡ de aÃ§afrÃ£o (1 g);\r\n33 unidades de alho (100 g);\r\n1 unidade de alho-porÃ³ (bulbo e parte inferior da folha) (90 g);\r\n4 xÃ­caras de chÃ¡ de arroz branco (800 g);\r\n10 ramos grandes de aspargo (200 g);\r\n6 colheres de sopa de azeite de oliva extra virgem (48 ml);\r\n400 gramas de peixe (badejo) em filÃ©;\r\n1 Kg de camarÃ£o sete barbas jÃ¡ limpo (sem cabeÃ§a);\r\n500 gramas de camarÃ£o VG jÃ¡ limpo (sem cabeÃ§a);\r\n1 Kg de camarÃ£o VG inteiro;\r\n500 gramas de camarÃ£o VM jÃ¡ limpo (sem cabeÃ§a);\r\n1 unidade grande de cebolinha verde (25 g);\r\n1/4 xÃ­cara de chÃ¡ de coentro fresco (4 g);\r\n250 gramas de ervilha em grÃ£o;\r\n5 unidades de lagosta (1 Kg);\r\n2 unidades de limÃ£o siciliano (120 g);\r\n500 gramas de lula em anÃ©is;\r\n1 Kg de mexilhÃ£o;\r\n1 colher de chÃ¡ de pimenta do reino (2 g);\r\n30 tiras de pimentÃ£o amarelo (156 g);\r\n3 fatias mÃ©dias de pimentÃ£o vermelho (165 g);\r\n1,250 Kg de polvo;\r\n1 colher de chÃ¡ de sal (6 g);\r\n3 colheres de sopa de salsa fresca (30 g);\r\n250 gramas de vagem;\r\n1 colher de chÃ¡ de pÃ¡prica (2 g);\r\n1 colher de chÃ¡ de gengibre em pÃ³ (2 g);', '1Âº\r\nAqueÃ§a uma frigideira especÃ­fica para Paella (ou uma que seja larga e funda) em fogo alto, adicione o azeite, e entÃ£o, os anÃ©is de lula temperados com sal e pimenta. Quando a lula ficar branca ela estarÃ¡ cozida. Reserve.\r\n2Âº\r\nAdicione mais azeite e refogue o alho-porÃ³ fatiado, e depois os dentes de alho esmagados. Coloque os temperos secos (aÃ§afrÃ£o, gengibre e pÃ¡prica picante) e misture. Adicione em seguida as ervas frescas: coentro, salsinha e cebolinha picadas.\r\n3Âº\r\nEm uma panela, coloque 2 litros de Ã¡gua para prepara um caldo com as aparas dos legumes, as cascas dos camarÃµes e as aparas do peixe. Reserve.\r\n4Âº\r\nCozinhe o polvo na panela de pressÃ£o por 11 minutos apenas com cebola, pimenta e sal. Depois de cozido, corte-o em cubos e reserve.\r\n5Âº\r\nAdicione o caldo coado na paellera, esprema o suco dos limÃµes. Junte o polvo, e depois os camarÃµes sete barbas e os camarÃµes VM (limpos, sem casca e sem cabeÃ§a, temperados com sal e pimenta).\r\n6Âº\r\nEm seguida, adicione o arroz e o badejo cortado em cubos (tambÃ©m temperado com sal e pimenta), e os anÃ©is de lula.\r\n7Âº\r\nAjuste o sal e a pimenta se necessÃ¡rio, e em seguida arrume de forma harmoniosa os demais ingredientes: aspargos e pimentÃµes jÃ¡ temperados e grelhados previamente, ervilhas, vagens, mexilhÃµes, camarÃµes e a lagosta (os frutos do mar jÃ¡ devem estar temperados com sal e pimenta).\r\n8Âº\r\nTampe a panela e aguarde atÃ© que esteja tudo cozido. Sirva na prÃ³pria panela.', 9, 15, 2, 116, '2022.11.16-16.33.51jpeg', NULL),
(66, ' SOPA DE LEGUMES', 'salgado', '2 unidades pequenas de batata (140 g);\r\n1 unidade mÃ©dia de cenoura crua (120 g);\r\n1 caule pequeno de salsÃ£o (aipo), cru (17 g);\r\n1 unidade pequena de cebola (30 g);\r\n1 dente de alho, cru (3 g);\r\n2 colheres de sopa cheias de aveia em flocos (30 g);', '1Âº\r\nLave todos os vegetais muito bem.\r\n2Âº\r\nDescasque as batatas, corte em cubinhos.\r\n3Âº\r\nCozinhe tudo com 4 copos de Ã¡gua exceto a aveia e o alho em fogo alto. acerte o sal\r\n4Âº\r\nBata no liquidificador os vegetais depois de cozidos junto com a Ã¡gua\r\n5Âº\r\nRefogue o alho com um fio de azeite, despeje o caldo e a aveia. Mexa atÃ© comeÃ§ar a ferver.', 18, 3, 1, 86, '2022.11.16-16.35.17jpeg', NULL),
(67, 'RECEITA GRANOLA CASEIRA', 'doce', '1 xÃ­cara de chÃ¡ de semente de girassol ou abÃ³bora (140 g);\r\n2 xÃ­caras de aveia em flocos grosso (160 g);\r\n1/2 xÃ­cara de semente de gergelim (70g);\r\n1 xÃ­cara de oleaginosas picadas (130g) (castanha do parÃ¡, caju, nos, amÃªndoa...);\r\n1 colher de chÃ¡ de canela em pÃ³ (3 g);\r\n1/2 xÃ­cara de chÃ¡ de coco em lascas (40 g);\r\n1/4 xÃ­cara de azeite de oliva exta-virgem (55 g);\r\n1/4 xÃ­cara de Ã³leo de coco (55g);\r\n1/3 xÃ­cara de aÃ§Ãºcar mascavo ou de coco (74g) (melado e mel nÃ£o ficam tÃ£o legais, viu? A granola nÃ£o fica tÃ£o crocante);\r\n1/2 xÃ­cara de uva passa (80g) e/ou damascos picados, cranberries, maÃ§Ã£ desidratada, frutas secas.;', '1Âº\r\nJunte em uma tigela todos os ingredientes, exceto as uvas passas (frutas secas).\r\n2Âº\r\nMisture bem e coloque em uma assadeira/forma.\r\n3Âº\r\nAsse em forno prÃ©-aquecido a 150C por 1h10. Adicione as frutas secas/uvas passas e misture.\r\n4Âº\r\nArmazene em potes hermÃ©ticos por atÃ© 2 meses.', 38, 11, 42, 554, '2022.11.16-16.37.09jpeg', NULL),
(68, 'ISCAS DE FRANGO CROCANTE', 'salgado', '600 gramas de sassami ou peito de frango;\r\n3 copos cheios de flocos de milho (90 g);\r\n5 colheres de sopa de amÃªndoas laminadas sem pele (46 g);\r\n5 colheres de sopa de sementes de gergelim (50 g);\r\n1 colher de sopa de pÃ¡prica picante ou defumada (7 g) , se preferir um sabor mais suave utilize a pÃ¡prica doce;\r\n1 pitada de sal;\r\n6 claras de ovos (198 g);\r\n120 ml de leite desnatado;\r\n5 colheres de sopa cheias de farinha de aveia (90 g);', '1Âº\r\nEm um processador de alimentos, triture grosseiramente os flocos de milho, as sementes de gergelim e as amÃªndoas. Transfira tudo para uma tigela e tempere com a pÃ¡prica, sal e pimenta do reino moÃ­da na hora e reserve.\r\n2Âº\r\nEm outro recipiente bata o leite com as claras e depois reserve.\r\n3Âº\r\nTempere as iscas (sassamis) com sal e pimenta do reino e reserve.\r\n4Âº\r\nPara empanar as iscas de frango, passe cada uma delas na farinha de aveia, retirando o excesso, e depois na mistura de claras e leite. Por fim, passe na mistura de flocos de milho, gergelim e amÃªndoas.\r\n5Âº\r\nPrÃ©-aqueÃ§a o forno a 160Â°C e leve as iscas empanadas para assar atÃ© que estejam douradas.', 14, 21, 7, 203, '2022.11.16-16.38.50jpeg', NULL),
(69, 'OMELETE PROTÃ‰ICO', 'Salgado', '2 unidades grandes de ovo de galinha (100 g);\r\n1 colher de sobremesa de azeite de oliva extra virgem (5 g);\r\n6 unidades de tomate cereja (102 g);\r\n2 colheres de sopa de manjericÃ£o fresco picado (5 g);\r\n1 pitada de pimenta do reino;\r\n1 pitada de sal;\r\n1 colher de sopa cheia de cebola ralada (10 g);\r\n1 dente de alho esmagado (3 g);\r\n50g de peito de frango cozido, temperado e desfiado;\r\n1 colher de sopa de cenoura ralada crua (10g);', '1Âº\r\nEm um tigela, use um fouet ou garfo para bater os ovos atÃ© estarem bem aerados. Tempere com uma pitada de sal e pimenta do reino.\r\n2Âº\r\nUse uma frigideira mÃ©dia antiaderente de fundo grosso. Ligue o fogo baixo, espalhe o azeite, refogue o alho e depois a cebola.\r\n3Âº\r\nJunte os ovos e em seguida distribua frango desfiado + os tomates e o manjericÃ£o.\r\n4Âº\r\nCozinhe por cerca de 4 minutos, e entÃ£o, vire a omelete ou tampe a frigideira para cozinhar a parte superior por mais 1 ou 2 minutos.', 3, 10, 6, 105, '2022.11.16-16.41.46jpeg', NULL),
(70, ' SORVETE DE ABACATE', 'doce', '1 unidade grande de abacate (900 g);\r\n1 garrafa de leite de coco (200 g);\r\nsuco de 1/2 limÃ£o e raspinhas da casca;\r\n2 colheres de chÃ¡ de xilitol ou aÃ§Ãºcar demerara (6 g);', '1Âº\r\nPique o abacate e coloque dentro de um liquidificador.\r\n2Âº\r\nAdicione o leite de coco, o xilitol, o suco e as raspas de limÃ£o\r\n3Âº\r\nBata tudo atÃ© que forme um creme bem homogÃªneo.\r\n4Âº\r\nTransfira para um recipiente, vede com papel filme e tampe\r\n5Âº\r\nLeve ao congelador. Quando o sorvete comeÃ§ar a firmar, bata na batedeira e volte ao congelador vedado com papel filme e uma tampa.\r\n6Âº\r\nDepois Ã© sÃ³ esperar algumas horas e pronto!\r\n7Âº\r\nDica: O leite de coco pode ser substituÃ­do por iogurte grego de kefir ou creme de leite fresco.', 6, 1, 9, 97, '2022.11.16-16.43.29jpeg', NULL),
(71, 'HambÃºrguer Fit', 'Salgado', 'PÃ£o integral redondo (50g);\r\n2 colheres de sopa de maionese de Abacate (31 g);\r\n1 porÃ§Ã£o de burguer Funcional (107 g);\r\n1 fatia grande de queijo minas light- FLAMBADO(40 g);\r\n1 tomate;\r\nFolhas de RÃºcula (30g);', '1. Corte o pÃ£o ao meio; \r\n2. Passe 1 colher de sopa de maionese de abacate em cada lado do pÃ£o; \r\n3. coloque 1 unidade do Burguer funcional; \r\n4. Para flambar o queijo minas, pode usar um maÃ§arico ou entÃ£o em uma frigideira bem quente (doure os dois lados e estÃ¡ pronto). Acrescente ao hambÃºrguer; \r\n5. Acrescente as folhas de rÃºcula e as rodelas de tomate;\r\n6. coloque a outra metade do pÃ£o e estÃ¡ pronto.', 29, 33, 11, 342, '2022.11.17-13.01.24.jpg', NULL),
(72, ' MIX DE CHIPS DE VEGETAIS', 'Salgado', '100 gramas de vagem;\r\n100 gramas de cenoura;\r\n100 gramas de beterraba;\r\n100 gramas de batata doce;\r\nSal a gosto;\r\n2 colheres de sopa de azeite de oliva extra virgem (16g).', '1. Descasque todos os vegetais, e corte em fatias bem finas. Coloque-os submersos em Ã¡gua bem fria em um recipiente;\r\n2. Frite na air fryer atÃ© ficar crocante;\r\n3. Tempere com uma pitada de sal, azeite de oliva e orÃ©gano Ã  gosto.', 14, 2, 4, 94, '2022.11.17-14.03.12.jpg', NULL),
(73, 'BATIDA DE BANANA COM GENGIBRE E MORANGO', 'Bebida', '1 unidade de banana prata crua (65 g);\r\n1 fatia de gengibre, cru (0,45g);\r\n4 unidades pequenas de morango congelado (28 g);\r\n1 copo pequeno cheio de Ã¡gua de coco (165 g) ou leite desnatado.', '1. Bata todos o ingredientes no liquidificador.\r\n2. Pode ser adoÃ§ado com mel ou adoÃ§ante stevia.\r\n3. Deve ser tomado logo apÃ³s o preparo.', 24, 1, 0, 101, '2022.11.17-14.10.42jpeg', NULL),
(74, ' SUCO VERDE DETOX', 'Bebida', '3 folhas mÃ©dias de couve manteiga crua (60 g);\r\n1 colher de chÃ¡ de condimento, gengibre, moÃ­do (2 g);\r\n1 unidade mÃ©dia de maÃ§Ã£ (152 g);\r\n1 colher de sopa de quinoa (12 g);\r\n1 copo pequeno cheio de Ã¡gua de coco (165 g).', '1. Bata todos os ingredientes no liquidificador e beba em seguida;\r\n2. NÃ£o Ã© necessÃ¡rio coar.', 17, 2, 1, 75, '2022.11.17-14.13.14jpeg', NULL),
(75, ' BOLO DE LARANJA', 'Doce', '2 unidades de ovo de galinha (90 g);\r\n6 colheres de chÃ¡ de xilitol (18 g);\r\n3 colheres de sopa de manteiga, sem sal (43 g);\r\n4 colheres de sopa cheias de farinha de aveia (72 g).', '1. Bata a manteiga com os ovos e o xilitol no liquidificador;\r\n2. Acrescente a aveia, farinha de trigo e o suco;\r\n3. Liquidifique mais , atÃ© misturar bem;\r\n4. Transfira a massa para um recipiente e acrescente o coco e o fermento e misture bem com um batedor de claras (fuÃª);\r\n5. Leve para assar em forno prÃ©-aquecido em uma forma untada com manteiga e xilitol ou aÃ§Ãºcar de coco;\r\n6. Fique de olho no forno e faÃ§a o teste do palito para saber se jÃ¡ estÃ¡ pronto.', 23, 5, 13, 210, '2022.11.17-14.15.32jpeg', NULL),
(76, 'SUCOS PARA IMUNIDADE', 'Bebida', '250ml de suco de laranja;\r\n1 folha mÃ©dia de couve;\r\nmeia cenoura;\r\n1 colher de sobremesa (5g) de semente de girassol;', '1. Bata todos os ingredientes no liquidificador e tome sem coar.', 38, 2, 3, 179, '2022.11.17-14.17.11jpeg', NULL),
(77, 'BRUSCHETTA DE TOMATE E QUEIJO', 'Salgado', '2 fatias de pÃ£o de forma de trigo integral (50 g);\r\n2 fatias pequenas de queijo minas (40 g);\r\n10 fatias mÃ©dias de tomate com semente cru (150 g);\r\n4 fatias pequenas de cebola crua (16 g);\r\n1 colher de sopa de gergelim semente (10 g);\r\n1 grama de Ã³regano;', '1. Monte as duas metades separadas, pode usar o pÃ£o francÃªs cortado ao meio tambÃ©m, se preferir, acrescente o queijo;\r\n2. Depois o tomate em fatias ou em cubinhos;\r\n3. A cebola Ã© opcional, e vocÃª tambÃ©m pode optar por acrescentar em rodelas ou em cubos;\r\n4. Salpique gergelim, orÃ©gano, e outros temperos que preferir e leve para airfryer por cerca de 10 min, a depender da potÃªncia e do ponto que preferir o pÃ£o;\r\n5. Para preparar sem a airfryer, vocÃª pode dourar o pÃ£o na frigideira, depois derreter o queijo se preferir e montar na mesma sequÃªncia.', 18, 8, 8, 162, '2022.11.17-14.19.51jpeg', NULL);
INSERT INTO `receitas` (`idreceitas`, `nome`, `tipo`, `ingredientes`, `modo_preparo`, `carboidrato`, `proteinas`, `gorduras`, `calorias`, `imagem`, `loginid`) VALUES
(78, ' BABAGANUCHE', 'Salgado', '1. PrÃ©-aqueÃ§a o forno a 220ÂºC. Unte uma assadeira com azeite. FaÃ§a cortes na polpa de cada metade da berinjela, sem atravessar a casca, e coloque-as na assadeira com o lado cortado para baixo. Asse por 25 a 30 minutos atÃ© a polpa ficar completamente macia, despedaÃ§ando;\r\n2. PrÃ©-aqueÃ§a o forno a 220ÂºC. Unte uma assadeira com azeite. FaÃ§a cortes na polpa de cada metade da berinjela, sem atravessar a casca, e coloque-as na assadeira com o lado cortado para baixo. Asse por 25 a 30 minutos atÃ© a polpa ficar completamente macia, despedaÃ§ando;\r\n3. Retire do forno. Descanse as berinjelas sob uma peneira por 15 minutos ou atÃ© esfriarem. Retire a polpa da berinjela e transfira para um processador;\r\n4. Adicione junto Ã  polpa de berinjela, o alho, o azeite, o iogurte, o tahine, o suco de limÃ£o. Bata atÃ© ficar homogÃªneo. Prove, ajuste adicionando mais suco de limÃ£o e/ou tahine, se necessÃ¡rio. Tempere com sal e pimenta-do-reino moÃ­da na hora;\r\n5. Pique as folhas de coentro. Polvilhe sobre o babaganuche. Regue com um fio de azeite. Mantenha refrigerado atÃ© 15 minutos antes de servir.', '2 unidades pequenas de berinjela cortada ao meio, no sentido do comprimento (916 g);\r\n2 dentes de alho grandes, descascados, crus (6 g);\r\n2 colheres de sopa de azeite de oliva extra virgem (16 g);\r\n2 colheres de sopa de iogurte natural;\r\n3 a 4 colheres de sopa de tahine/pasta de gergelim (64 g);\r\n2 a 3 colheres de sopa de suco de limÃ£o;\r\n9 raminhos de folha de coentro fresco (20 g);\r\n1 colher de chÃ¡, moÃ­do de condimento, pimenta do reino (2 g).', 15, 5, 10, 158, '2022.11.17-14.22.28jpeg', NULL),
(79, 'TABULE', 'Salgado', '115 gramas de trigo para quibe;\r\n2 unidades de limÃ£o siciliano (120 g);\r\n20 ml de azeite de oliva;\r\n225 gramas de salsa fresca;\r\n75 gramas de hortelÃ£ fresco;\r\n4 unidades mÃ©dias de cebolinha verde (60 g);\r\n2 unidades grandes de tomate (364 g);\r\n1 unidade pequena de alface (130 g);\r\n1 pitada de pimenta do reino;\r\n1 pitada de sal.', '\r\n1. Coloque o trigo para quibe em uma tigela grande e cubra com Ã¡gua fria. Deixe que descanse por cerca de 15 minutos, ou atÃ© que tenha absorvido a Ã¡gua completamente;\r\n2. Tempere o trigo com o suco de limÃ£o, azeite, pimenta do reino e sal a gosto;\r\n3. Descarte os talos e pique bem a cebolinha, a hortelÃ£ e a salsa. Incorpore-as ao tabule;\r\n4. Corte os tomates em cubos, descartando as sementes. Reserve;\r\n5. Solte as folhas do alface, higienize uma a uma. Reserve;\r\n6. Sirva o tabule gelado, nas folhas de alface, com os tomates em cubos por cima.', 23, 5, 4, 136, '2022.11.17-14.27.04jpeg', NULL),
(80, 'ESPAGUETE DE ABOBRINHA COM ATUM', 'Salgado', '160 gramas de abobrinha crua;\r\n2 latas de atum em conserva (240 g);\r\n1 colher de sopa de molho de tomate (20 g);\r\n1 fatia mÃ©dia de queijo ricota (35 g);\r\n5 folhas de manjericÃ£o, fresco (3 g);\r\n1 pitada de sal, cozinha (0 g).', '\r\n1. Lave as abobrinhas e corte em fios com um descascador. Se vocÃª nÃ£o possui um, pode ralÃ¡-las;\r\n2. Em uma panela pequena, misture o molho de tomate com a Ã¡gua (quanto menos Ã¡gua, mais grosso ficarÃ¡ o seu molho);\r\n3. Quando vocÃª atingir a consistÃªncia do molho desejada, adicione o atum (ou outra proteÃ­na de sua preferÃªncia) e os temperos a gosto e cozinhe;\r\n4. Quando ferver, despeje-o sobre o â€œespagueteâ€ de abobrinha.', 2, 17, 5, 123, '2022.11.17-14.29.16jpeg', NULL),
(81, 'VITAMINA DE BANANA', 'Bebida', '1 unidade de banana prata crua (65 g);\r\n100 ml de leite de vaca integral ou 100 ml de leite semi-desnatado;\r\n2 colheres de sopa cheias de aveia em flocos (30 g);', '1. Corta a banana prata madura em rodelas e colocar no liquidificador;\r\n2. adicionar leite( integral ou semi desnatado) no liquidificador;\r\n3. adicionar duas colheres de sopa cheia de aveia em flocos no liquidificador;\r\n4. Sirva em copo de sua preferÃªncia.', 35, 8, 4, 198, '2022.11.17-14.32.13jpeg', NULL),
(82, 'MINGAU DE AVEIA', 'Doce', '2 colheres de sopa cheias de farinha de aveia (36 g);\r\n80 gramas de leite de vaca integral;\r\n1 unidade de banana prata crua (65 g)', '1. Pique a banana em pedaÃ§os, do tamanho que preferi;\r\n2. Misture todos os ingredientes e leve ao fogo baixo, mexendo sempre;\r\n3. Quando atingir uma consistÃªncia pastosa, desligue o fogo e enfeite como quiser;\r\n4. Ã‰ possÃ­vel acrescentar outras frutas por cima, mel, pedaÃ§os de chocolate, pasta de amendoim, whey, uva passa, etc.', 45, 9, 5, 250, '2022.11.17-14.33.46jpeg', NULL),
(83, 'OSSOBUCO', 'Salgado', '500 gramas de mÃºsculo bovino sem gordura (2 peÃ§as de 250 g no corte ossobuco);\r\n1 colher de sopa cheia de cenoura cortada em cubos (12 g);\r\n1/4 de aipo cortado em cubos (12 g);\r\n1 unidade pequena de cebola (30 g);\r\n1 dente de alho esmagado (3 g);\r\n1 colher de sopa cheia de farinha de trigo (7 g);\r\n1 colher de sopa de manteiga sem sal (14 g)\r\n60 ml de vinho branco;\r\n1 colher de sopa de molho de tomate (20 g)\r\n500 ml de Ã¡gua;\r\n1 colher de sopa de salsinha fresca picada (4 g);\r\n1 colher de chÃ¡ de raspas de limÃ£o (5 g);\r\n1 colher de chÃ¡ de raspas de laranja (5 g);\r\n1 colher de chÃ¡ de sal (6 g);\r\n1 colher de chÃ¡ de pimenta do reino (2 g).', '1. Tempere a carne com sal e pimenta do reino. Em seguida, passe-a na farinha removendo o excesso. Reserve;\r\n2. Em uma frigideira larga e alta derreta a manteiga. Adicione o ossobuco e doure os dois lados, atÃ© formar uma crosta. Retire as peÃ§as de ossobuco e reserve em um recipiente tampado;\r\n3. Na frigideira, refogue o alho e em seguida a cebola. Junte a cenoura e o aipo. Cozinhe em fogo mÃ©dio-baixo por 10 minutos, mexendo ocasionalmente. Transfira para uma assadeira com ao ossobuco;\r\n4. Na mesma frigideira, coloque o vinho branco e deixe em fogo baixo atÃ© quase estar seco. Junte o molho de tomate e cozinhe atÃ© engrossar. Transfira para a assadeira;\r\n5. Acrescente 500 ml de Ã¡gua ou caldo de carne caseiro. Cubra a assadeira com papel alumÃ­nio e asse em forno prÃ©-aquecido a 200 ÂºC por 2 horas. Retire o papel alumÃ­nio, junte as raspas de limÃ£o e laranja e sirva.', 3, 18, 7, 154, '2022.11.17-14.35.50jpeg', NULL),
(84, ' PÃƒO DE MACAXEIRA', 'Salgado', '120 gramas de macaxeira cozido;\r\n1 unidade de ovo de galinha (45 g);\r\n2 gramas de tablete de fermento biolÃ³gico, levedura;\r\n1 grama de tempero a base de sal.', '1. Cozinhe a macaxeira. Deixe esfriar por 12 minutos\r\n2. Triture no liquidificador ou processador.\r\n3. Acrescente o ovo, fermento e sal e misture bem.\r\n4. Coloque em uma xÃ­cara de porcelana e levar ao forno micro-ondas por 4 minutos.', 191, 5, 4, 33, '2022.11.17-14.39.30jpeg', NULL),
(85, ' SHAKE PROTEICO DE AÃ‡AÃ, MORANGO E MAMÃƒO', 'Doce', '150 gramas de Ã¡gua;\r\n50 gramas de AÃ§aÃ­ Frooty Zero;\r\n10 unidades mÃ©dias de morango (120 g);\r\n1 fatia de mamÃ£o Papaia cru (170 g);\r\n2 medidores de whey protein isolado (30 g) ou30 gramas de proteÃ­na vegetal.', '1. Bata os ingredientes no liquidificador. Beba em seguida.', 15, 9, 2, 102, '2022.11.17-14.41.15jpeg', NULL),
(86, 'PORCO Ã€ MODA MEXICANA', 'Salgado', '3 porÃ§Ãµes de pernil suÃ­no (300 g);\r\n50 ml de suco de laranja;\r\n1 colher de chÃ¡ de orÃ©gano desidratado (1 g);\r\n1 colher de chÃ¡ de cominho (2 g);\r\n2 colheres de chÃ¡ de vinagre de vinho (10 ml);\r\n1 colher de sopa de colorau em pÃ³ (2 g);\r\n2 colheres de sopa de azeite de oliva extra virgem (16 ml);\r\n1 unidade pequena de cebola (30 g);\r\n1 colher de chÃ¡ de sal (6 g);\r\n1 colher de chÃ¡ de pimenta dedo de moÃ§a picada (2 g) (opcional).', '1. Tempere o pernil suÃ­no com sal e pimenta do reino. Reserve;\r\n2. Em uma panela aqueÃ§a o azeite. Desligue o fogo e adicione o colorau em pÃ³. Deixe descansar atÃ© o azeite estar bem pigmentado. Transfira o azeite para um processador de alimentos, adicionando o suco de laranja, o orÃ©gano, o cominho e o vinagre. Processe tudo e, em seguida, espalhe pelo pernil suÃ­no;\r\n3. Forre uma assadeira com papel alumÃ­nio suficiente para fechar e embrulhar a carne. Arrume o pernil e espalhe a cebola fatiada ou em anÃ©is por cima da carne. Feche com o papel alumÃ­nio e deixe marinar por 30 minutos;\r\n4. PrÃ©-aqueÃ§a o forno a 200ÂºC e leve o pernil suÃ­no para assar por 4 horas;\r\n5. Abra o forno e desembrulhe a carne. Corte em fatias, e entÃ£o, desfaÃ§a em lascas. Envolva toda a carne com o caldo do cozimento.', 3, 15, 12, 191, '2022.11.17-14.44.37jpeg', NULL),
(87, 'CAMARÃ•ES Ã€ MODA MARROQUINA', 'Salgado', '16 unidades grandes de camarÃ£o limpo (sem casca e sem cabeÃ§a) (480 g);\r\n4 colheres de sopa de azeite de oliva extra virgem (32 ml);\r\n1/2 colher de chÃ¡ de pÃ¡prica doce e 1/2 colher de chÃ¡ de pÃ¡prica picante (2 g);\r\n1 colher de chÃ¡ de gengibre em pÃ³ (2 g);\r\n1 colher de chÃ¡ de cominho em pÃ³ (2 g);\r\n1/2 colher de chÃ¡ de coentro em pÃ³ (1 g);\r\n3 dentes de alho esmagados ou em pasta (9 g);\r\n1 colher de sopa de salsa fresca (10 g);\r\n1 colher de sopa de coentro fresco (10 g);\r\n4 fatias mÃ©dias de abacaxi (300 g).', '1. Em uma frigideira larga, antiaderente e com as laterais altas, adicione o azeite e os temperos e ligue o fogo bem baixo. Deixe apurar os sabores por cerca de 1 minuto quando comeÃ§ar a aquecer. Retire da frigideira e reserve;\r\n2. Aumente o fogo, aproveite o azeite e junte os camarÃµes, deixe fritar por 2 minutos de cada lado, em fogo mÃ©dio-alto. Volte com as ervas e temperos e desligue o fogo. Reserve;\r\n3. Pique as fatias de abacaxi em quatro triÃ¢ngulos, desprezando o miolo. Em uma frigideira, doure-as bem dos dois lados;\r\n4. Use espetos para churrasco para arrumar os camarÃµes, alternando com o abacaxi.', 8, 18, 6, 157, '2022.11.17-14.47.22jpeg', NULL),
(88, 'MOLHO PESTO', 'Salgado', '1. No processador de alimentos, triture o pinoli (ou a castanha de sua preferÃªncia), o alho e o queijo parmesÃ£o;\r\n2. Adicione o azeite e misture no processador atÃ© ficar homogÃªneo. Tempere com sal e pimenta a gosto.', '50 gramas de pinoli (ou outra oleaginosa de sua preferÃªncia - noz, castanha de caju ou castanha do Brasil);\r\n3 unidades de alho (9 g);\r\n3 pratos de sobremesa de manjericÃ£o fresco (90 g);\r\n4 colheres de sopa cheias de queijo parmesÃ£o ralado (60 g);\r\n6 colheres de sopa de azeite de oliva extra virgem (48 ml);\r\n1 colher de chÃ¡ de sal (6 g);\r\n2 colheres de chÃ¡ de pimenta do reino (5 g).', 7, 12, 37, 391, '2022.11.17-14.49.25jpeg', NULL),
(89, 'FONDUE DE QUEIJO', 'Salgado', '1 caixinha de creme de leite (200 g);\r\n50 gramas de queijo parmesÃ£o ralado;\r\n150 gramas de queijo gruyere ou emmental ralado;\r\n10 ramos pequenos de couve-flor jÃ¡ cozida (300 g);\r\n10 ramos de brÃ³colis jÃ¡ cozido (370 g);\r\n1 pitada de sal;\r\n1 pitada de pimenta do reino branca;\r\n1/2 colher de chÃ¡ de noz-moscada moÃ­da ou ralada na hora (1 g).', '1. Em uma panela, ferva o creme de leite e tempere com sal, pimenta do reino branca e noz moscada;\r\n2. Desligue o fogo e junte o queijo, mexa bem atÃ© que esteja todo derretido. Sirva em um recipiente para fondue.', 9, 13, 21, 268, '2022.11.17-14.53.11jpeg', NULL),
(90, 'SORVETE DE MANGA FIT', 'Doce', '1 unidade de banana prata crua (65 g);\r\n8 gramas de gengibre, cru;\r\n2 unidades pequenas de manga (240 g);\r\n2 folhas de hortelÃ£, fresco (0 g);\r\n1 unidade mÃ©dia de iogurte desnatado (200 g).', '1. liquidificador;\r\n2. Preparo Em primeiro lugar coloque todos os ingredientes (menos a hortelÃ£) no liquidificador ou processador e bata aos poucos, desligue algumas vezes, mexa com uma colher e volte a bater. Em seguida quando adquirir consistÃªncia homogÃªnea coloque em taÃ§as e sirva com hortelÃ£ picadinha por cima. Se preferir coloque as taÃ§as no congelador para endurecer um pouco mais antes de servir.', 24, 5, 0, 111, '2022.11.17-14.55.45jpeg', NULL),
(91, ' CRÃˆME CARAMEL - PUDIM DE LEITE', 'Doce', '160 gramas de aÃ§Ãºcar refinado;\r\n75 gramas de Ã¡gua SÃ£o Martinho;\r\n1000 gramas de leite de vaca integral;\r\n1 colher de chÃ¡ de extrato de baunilha (4 g)\r\n180 gramas de aÃ§Ãºcar refinado;\r\n6 unidades grandes de gema, crua (102 g);\r\n240 gramas de ovo de galinha cru (4 ovos).', '1. Para a calda de caramelo: Numa panela, derreta 160 gramas de aÃ§Ãºcar, junte a Ã¡gua, mexa cuidadosamente. Distribua o caramelo em ramequins;\r\n2. Numa panela, ferva o leite com a baunilha e 90g de aÃ§Ãºcar. Ã€ parte, bata 90g de aÃ§Ãºcar com as gemas e os ovos, atÃ© ficar homogÃªneo. Despeje, aos poucos, o leite fervido nesta mistura. Mexa sempre;\r\n3. PrÃ©-aqueÃ§a o forno a 165ÂºC. Distribua a massa nas forminhas caramelizadas. Asse em banho-maria cerca de 35 minutos, atÃ© estar firme. Deixe esfriar e leve Ã  geladeira por 6 horas. Desenforme e sirva.', 22, 5, 5, 149, '2022.11.17-14.57.43jpeg', NULL),
(92, ' ESPAGUETE COM MOLHO DE TOMATE CASEIRO ESPECIAL', 'Salgado', '375 gramas de macarrÃ£o de arroz tipo espaguete;\r\n1 kg de tomates frescos sem pele e nem sementes;\r\n1 cebola bem picada;\r\n1 colher de chÃ¡ de aÃ§Ãºcar;\r\n1 folha de louro;\r\nSal, azeitonas pretas e pimenta do reino a gosto\r\nAzeite de oliva extravirgem para refogar\r\nManjericÃ£o e tomates-cereja cortados ao meio para acompanhar.', '1. MOLHO - BATA NO LIQUIDIFICADOR OS TOMATES SEM PELE ATÃ‰ ATINGIR UMA TEXTURA MAIS LÃQUIDA. SE QUISER UM MOLHO AINDA MAIS LÃQUIDO E SEM GRUMOS, BASTA PASSÃ-LO NA PENEIRA;\r\n\r\n2. FEITO ISSO, CUBRA O FUNDO DE UMA PANELA COM AZEITE DE OLIVA E REFOGUE A CEBOLA PICADA. Ã‰ IMPORTANTE QUE FIQUE BEM DOURADA PARA QUE TRANSFIRA TODO SEU AROMA PARA O MOLHO.\r\n3. ADICIONE O TOMATE BATIDO,O LOURO, O SAL, AS AZEITONAS PRETAS E A PIMENTA DO REINO. ACERTE O SABOR ADICIONANDO O AÃ‡ÃšCAR. DEIXE COZINHAR EM FOGO BRANDO POR 10 MINUTOS OU ATÃ‰ O MOLHO ENCORPAR;\r\n\r\n4. MASSA - COLOQUE O MACARRÃƒO EM ÃGUA FERVENTE COM UM FIO DE AZEITE. LEVE A FOGO BRANDO E DEIXE COZINHAR ATÃ‰ A MASSA ATINGIR O PONTO AL DENTE. RETIRE DO FOGO E ESCOE A ÃGUA. ADICIONE O MOLHO DE TOMATE E DECORE O PRATO COM FOLHAS DE MANJERICÃƒO E TOMATES-CEREJA CORTADOS AO MEIO.', 34, 4, 3, 173, '2022.11.17-15.00.17jpeg', NULL),
(93, 'GUACAMOLE COM PIMENTA DEDO-DE-MOÃ‡A', 'Salgado', '1 unidade pequena de abacate (370 g);\r\n2 unidades mÃ©dias de tomate italiano sem pele, cortado em cubos (200 g);\r\n1 unidade pequena de cebola roxa cortada em cubinhos ou ralada (30 g);\r\n1/4 xÃ­cara de chÃ¡ de coentro, folhas frescas e picadas (4 g);\r\n1 colher de chÃ¡ de pimenta dedo-de-moÃ§a picadinha (2 g);\r\nSuco de meio limÃ£o (33 g);\r\n1 colher de chÃ¡ de Tabasco (5 g).', '1. Corte os tomates ao meio, no sentido do comprimento. Com uma faquinha, retire miolo e sementes e descarte-os. Pique os tomates em cubinhos;\r\n2. O abacate deve estar bem maduro. Para abrÃ­-lo facilmente, passe a faca, no sentido do comprimento, no meio dele atÃ© encontrar o caroÃ§o. Gire uma metade contra a outra e elas devem se soltar. DÃª uma batidinha com a faca no caroÃ§o para soltÃ¡-lo. Com as mÃ£os ou uma faquinha, retire a casca do avocado (quando ele estÃ¡ bem maduro, a casca sai com a mÃ£o mesmo). Coloque o avocado em uma tigela, amasse com um garfo, jogue o suco de limÃ£o e deixe o caroÃ§o junto. Deixar o caroÃ§o no abacate amassado Ã© o segredo para ele nÃ£o escurecer, assim ele dura 24h na geladeira em perfeito estado;\r\n3. Misture todos os ingredientes e tempere bem. Conserve o caroÃ§o inclusive enquanto estiver misturando e sÃ³ retire-o da mistura quando for servir. Se quiser guardar a guacamole na geladeira por atÃ© um dia, deixe o caroÃ§o junto e ela nÃ£o vai escurecer nem um pouquinho;\r\n4. Tempere com sal e pimenta-do-reino moÃ­da.', 8, 2, 7, 91, '2022.11.17-15.02.20jpeg', NULL),
(94, ' LEITE CONDENSADO CASEIRO', 'Doce', '1 xÃ­cara de leite em pÃ³ desnatado;\r\n1/2 xÃ­cara de Ã¡gua fervente;\r\n1/2 xÃ­cara de adoÃ§ante em pÃ³ culinÃ¡rio;\r\n1 colher de sopa de manteiga, sem sal (14 g).', '1. Bata todos os ingredientes no liquidificador por 5 minutos;\r\n2. Mantenha a receita na geladeira', 28, 5, 3, 160, '2022.11.17-15.03.37jpeg', NULL),
(95, 'SALADA WALDORF', 'Salgado', '4 caules mÃ©dios de salsÃ£o/aipo (160 g);\r\n10 unidades de nozes (50 g);\r\n2 colheres de chÃ¡ de cerefÃ³lio seco (1 g);\r\n1 pitada de pimenta do reino;\r\n2 unidades mÃ©dias de maÃ§Ã£ verde sem casca (322 g);\r\n1 cabeÃ§a de alface (626 g);\r\n11 unidades mÃ©dias de uva rubi sem semente (88 g);\r\n1 dente de alho (3 g);\r\n1/2 colher de chÃ¡ de sal (3 g);\r\n3 colheres de sopa rasas de maionese (51 g);\r\n1 colher de sobremesa cheia de iogurte natural (17 g).', '1. Solte as folhas da alface cuidadosamente, lave uma a uma, deixe secar. Reserve;\r\n2. Descasque as maÃ§Ã£s verdes, pique em cubos de aproximadamente 1 cm. Reserve em uma tigela com Ã¡gua gelada para nÃ£o escurecer;\r\n3. Corte os talos de salsÃ£o/aipo em pedaÃ§os de aproximadamente 1 cm e reserve;\r\n4. Corte as nozes grosseiramente. Reserve;\r\n5. Em um processador de alimentos, junte a maionese, o iogurte, o alho descascado e amassado. Misture bem. Ajuste com o sal, e reserve o molho;\r\n6. Para montar a salada: arrume as folhas de alface, coloque os pedaÃ§os de salsÃ£o, maÃ§Ã£ e nozes. Despeje o molho sobre os ingredientes, envolvendo-os bem. Por fim adicione o cerefÃ³lio e tempere com pimenta do reino. Use as uvas cortadas ao meio para decorar o prato.', 10, 2, 4, 79, '2022.11.17-15.05.44jpeg', NULL),
(96, 'PENNE PRIMAVERA', 'Salgado', '450 gramas de macarrÃ£o cozido (penne, rigatoni ou fusilli);\r\n350 gramas de brÃ³colis (quebrados com as mÃ£os para que fiquem menores e mais delicados);\r\n2 unidades grandes de cenoura descascadas e cortadas em tiras finas (270 g);\r\n1 unidade pequena de abobrinha italiana descascada e picada (118 g);\r\n8 colheres de sopa cheias de vagem picada (160 g);\r\n2 colheres de sopa de manjericÃ£o fresco picado grosseiramente (5 g);\r\n1 colher de chÃ¡ de folhas de orÃ©gano fresco ou desidratado (1 g);\r\nSal a gosto;\r\n1 pitada de pimenta do reino preta ou branca;\r\n50 ml de azeite de oliva extra virgem;\r\n3 colheres de chÃ¡ de vinagre de vinho branco (15 g);\r\n1 colher de sobremesa rasa de mostarda Dijon (9 g);\r\n1 colher de chÃ¡ de alho amassado (3 g).', '1. Em uma panela alta, adicione Ã¡gua suficiente para cobrir todo o macarrÃ£o. Deixe a Ã¡gua ferver, adicione uma colher de chÃ¡ de sal, e entÃ£o, o macarrÃ£o. Cozinhe por 12 minutos e desligue o fogo. Com auxÃ­lio de um escorredor de macarrÃ£o, escorra a Ã¡gua de cozimento;\r\n2. Enquanto isso, em uma frigideira, use azeite e sal para refogar os vegetais separadamente, por cerca de 5 minutos, ou atÃ© estarem macios mas ainda crocantes e sem desmanchar. Reserve cada um deles;\r\n3. No processador de alimentos, junte o vinagre de vinho branco, a mostarda Dijon e o alho amassado e misture bem. Adicione o azeite aos poucos, misturando atÃ© emulsionar e formar o molho. Prove, ajuste com sal e pimenta do reino. Se for necessÃ¡rio, corrija a acidez com um pouco mais de azeite;\r\n4. Em um recipiente grande, incorpore delicadamente o macarrÃ£o, os vegetais, o molho, o manjericÃ£o e o orÃ©gano. Ajuste o sal e pimenta se necessÃ¡rio.', 19, 4, 6, 141, '2022.11.17-15.07.38jpeg', NULL),
(97, ' BRIGADEIRO DE CHOCOLATE BELGA (AO LEITE)', 'Doce', '1 lata de leite condensado (395 g);\r\n2 colheres de sopa cheias de creme de leite (40 g);\r\nchocolate ao leite (60 g, picado em cubos);\r\nchocolate meio amargo (20 g, picado em cubos);\r\n2 colheres de sobremesa cheias de chocolate em pÃ³ 50% cacau (20 g).', '1. Em uma panela mÃ©dia de fundo grosso e cabo de madeira, coloque o leite condensado e o chocolate em pÃ³, misture bem atÃ© estar homogÃªneo. Adicione o creme de leite, mexa bem, adicione o chocolate ao leite e amargo em cubos, mexa bem;\r\n2. Ligue o fogo em chama mÃ©dia-baixa e cozinhe atÃ© ferver, mexendo sempre com uma espÃ¡tula de silicone. Assim que iniciar fervura, baixe o fogo e continue mexendo, batendo bem com a espÃ¡tula para que nÃ£o forme grumos e raspando as laterais para que nÃ£o queime;\r\n3. ApÃ³s dez minutos o brigadeiro jÃ¡ deve estar no ponto correto. Para avaliar o ponto, levante a espÃ¡tula de silicone, deixando escorrer o brigadeiro, que deve cair em blocos atÃ© estabilizar na colher;\r\n4. Desligue o fogo. Despeje o brigadeiro da panela em um prato untado com manteiga. Cubra com filme plÃ¡stico;\r\n5. Leve ao freezer e deixe atÃ© esfriar. Se quiser congelar a massa, transfira para um potinho higienizado, cubra com filme plÃ¡stico retirando bem o ar, e entÃ£o tampe. Pode manter congelado por atÃ© 30 dias ou ultracongelado (-18ÂºC) por atÃ© 60 dias;\r\n6. Para moldar e confeitar o brigadeiro, retire a massa do freezer e deixe pelo menos 2 horas na geladeira. ApÃ³s descongelar, retire da geladeira e deixe chegar Ã  temperatura ambiente para sÃ³ entÃ£o moldar;\r\n7. Divida a massa de brigadeiro em porÃ§Ãµes de 15 gramas. Unte as mÃ£es com manteiga e boleie cada porÃ§Ã£o;\r\n8. Em um bolw Ã  parte, coloque um pouco de chocolate granulado callebaut Split 9M ao leite. Passe os brigadeiros atÃ© estarem completamente cobertos e coloque nas forminhas nÂº5.', 55, 7, 11, 339, '2022.11.17-15.10.36jpeg', NULL),
(98, ' LENTILHAS AROMÃTICAS DA PRIMAVERA', 'Salgado', '500 gramas de lentilha crua;\r\n1 unidade mÃ©dia de cenoura crua cortada em pequenos cubos (120 g);\r\n1 unidade pequena de cebola crua (30 g);\r\n3 unidades de alho cru (9 g);\r\nfolhas alecrim, fresco OU tomilho;\r\n1 colher de chÃ¡ de condimento, semente de cominho (2 g);\r\n1 colher de sopa de azeite de oliva extra virgem (8 g);\r\nSal e pimenta Ã  gosto.', '1. Mergulhe a lentilha por pelo menos 1 hora em Ã¡gua morna. Escorra e lave-as;\r\n2. Adicione o alecrim, tomilho e alho. Cubra em Ã¡gua e deixe ferver por 20 - 30 minutos atÃ© ficarem consistentes. Adicione mais Ã¡gua se necessÃ¡rio;\r\n3. Em outra panela, adicione 2 colheres de sopa de azeite, cebola e as cenouras. Frite atÃ© que a cebola fique transparente;\r\n4. Continue mexendo e adicione lentamente as lentilhas. Adicione cominho, sal e pimenta. Cozinhe por mais alguns minutos atÃ© reduzir o excesso de Ã¡gua.', 54, 20, 2, 304, '2022.11.17-15.12.43jpeg', NULL),
(99, 'CANJICA DOCE ', 'Doce', '500 gramas de canjica branca crua;\r\n3000 gramas de Ã¡gua mineral natural;\r\n2 latas de leite condensado (790 g);\r\n1 xÃ­cara de chÃ¡ de aÃ§Ãºcar refinado (170 g);\r\n2 colheres de sopa de margarina;\r\n50 gramas de coco seco, ralado;\r\n2 paus de canela;\r\n6 cravos da Ãndia.', '1. Escolha a canjica e deixe de molho em Ã¡gua morna por 4 horas. Escorra;\r\n4. Ferva 3 litros de Ã¡gua;\r\n5. Em uma panela de pressÃ£o, junte a Ã¡gua e a canjica. Tampe. Ligue o fogo atÃ© pegar pressÃ£o. Abaixe o fogo e cozinhe 60 minutos;\r\n6. Transfira a canjica para uma panela grande. Junte o leite condensado, o aÃ§Ãºcar, o coco ralado, a margarina, a canela e os cravos;\r\n7. Cozinhe mexendo constantemente atÃ© engrossar o caldo;\r\n8. Sirva quente ou gelada, com canela em pÃ³, paÃ§oca ou amendoim torrado.', 22, 2, 3, 121, '2022.11.17-15.14.39jpeg', NULL),
(100, 'MOUSSE DE CACAU EM PÃ“', 'Doce', '1.5 copos duplos cheios de leite de vaca desnatado (360 g);\r\n1/2 envelope de gelatina sem sabor, incolor;\r\n3 colheres de sopa de cacau, pÃ³ seco, sem adoÃ§ante (16 g);\r\n1 colher de sopa de mel (15 g);\r\n2 claras de ovo de galinha cru;\r\n1 colher de sopa de cacau em pÃ³ para polvilhar.', '1. No liquidificador, bata o leite (ou leite vegetal), a gelatina, o cacau e o mel. Reserve;\r\n2. Na batedeira, bata as claras em neve e junte delicadamente Ã  mistura de chocolate; \r\n3. Distribua em trÃªs taÃ§as e leve Ã  geladeira por 1 hora ou atÃ© ficar firme e geladinho. Sirva polvilhado com o cacau em pÃ³.', 15, 22, 1, 150, '2022.11.17-15.16.25jpeg', NULL),
(101, 'FEIJOADA', 'Salgado', '150 gramas de rabo suÃ­no;\r\n150 gramas de costela suÃ­na;\r\n200 gramas de orelha suÃ­na;\r\n200 gramas de lombo suÃ­no;\r\n150 gramas de carne seca;\r\n150 gramas de paio;\r\n150 gramas de linguiÃ§a portuguesa ou calabresa;\r\n150 gramas de lÃ­ngua bovina;\r\n150 gramas de lÃ­ngua suÃ­na;\r\n150 gramas de pÃ© suÃ­no;\r\n1 kg de feijÃ£o preto cru;\r\n200 gramas de cebola picada;\r\n100 gramas de alho cru amassado;\r\n1 colher de sobremesa de pimenta dedo de moÃ§a (5 g);\r\n4 folhas de louro;\r\ncebolinha verde fresca picada;\r\n1 dose de aguardente (50 g);\r\nmeia xÃ­cara de chÃ¡ (125 gramas) de suco concentrado de laranja.', '1. Deixe as carnes e os feijÃµes de molho 24 horas, trocando a Ã¡gua vÃ¡rias vezes.;\r\n2. Em um caldeirÃ£o bem grande o feijÃ£o e cubra com Ã¡gua ou fundo de carne. Juste o louro, as carnes e deixe cozinhar;\r\n3. Ã€ parte, refogue em uma panela a calabresa. Reserve. Adicione a aguardente Ã  panela para deglaÃ§ar o fundo. Deixe evaporar bem o Ã¡lcool. Aproveite a mesma panela para refogar a pimenta, o alho e a cebola. Junte ao feijÃ£o. Deixe cozinhar atÃ© o feijÃ£o e as carnes estarem macios, e o caldo, espesso. Desligue o fogo e adicione o suco de laranja ao final, para nÃ£o amargar.', 21, 19, 13, 278, '2022.11.17-15.18.17jpeg', NULL),
(102, 'COULIS DE MORANGO', 'Doce', '500 gramas de morango processado;\r\n150 gramas de aÃ§Ãºcar refinado peneirado;\r\n150 gramas de Ã¡gua SÃ£o Martinho.', '1. FaÃ§a uma calda de aÃ§Ãºcar e adicione a fruta processada para cozinhar atÃ© a consistÃªncia de um purÃª ralo de frutas', 23, 1, 0, 91, '2022.11.17-15.20.35jpeg', NULL),
(103, 'SALADA GREGA VEGANA', 'Salgado', '16 folhas exteriores de alface (448 g);\r\n15 unidades de tomate cereja (255 g);\r\n95 fatias pequenas de pepino (285 g);\r\n1 unidade mÃ©dia de cebola roxa em fatias (70 g);\r\n100 gramas de tofu;\r\n27 unidades mÃ©dias de azeitona preta (81 g);\r\n20 unidades mÃ©dias de azeitona verde (80 g);\r\n60 ml de suco de limÃ£o;\r\n1 colher de sopa de salsa fresca (10 g);\r\n1 colher de chÃ¡ de molho de mostarda (3 g);\r\n1 fatia pequena de cebola ralada ou bem picada (4 g);\r\n1 colher de chÃ¡ cheia de aÃ§Ãºcar mascavo (4 g);\r\n80 ml de azeite de oliva extra virgem;\r\n5 folhas de manjericÃ£o fresco (3 g);\r\n1 colher de chÃ¡ de estragÃ£o desidratado moÃ­do (2 g);\r\n1 colher de chÃ¡ de orÃ©gano desidratado moÃ­do (1 g);\r\n1 colher de sopa de cebolinha picada (6 g).', '1. Lave as folhas de alface uma a uma, depois rasgue cada folha com as mÃ£os;\r\n2. Arrume as folhas de alface em um refratÃ¡rio redondo ou oval, distribuindo o tomate partido ao meio, o pepino, a cebola, o tofu e as azeitonas. Distribua o molho e sirva;\r\n\r\n3. Molho: Com o auxÃ­lio de um mixer, combine o suco de limÃ£o, a mostarda, a cebola ralada e o aÃ§Ãºcar. Tempere com sal e pimenta do reino. Junte o azeite aos poucos, enquanto bate a mistura. Junte as ervas (salsa, manjericÃ£o, estragÃ£o, orÃ©gano e cebolinha). Mantenha na geladeira caso nÃ£o sirva imediatamente.', 4, 1, 8, 84, '2022.11.17-15.22.59jpeg', NULL),
(104, 'PATÃŠ DE BERINJELA COM FARINHA DE LINHAÃ‡A', 'Salgado', '2 unidades de berinjelas;\r\n1 dente de alho;\r\n1 unidade mÃ©dia de cebola (70 g);\r\n1 colher de sopa de azeite de oliva (8 g);\r\n5 colheres de sopa de semente de linhaÃ§a (50 g);\r\n2 pitadas de condimento, pimenta do reino (0 g);\r\n2 gramas de sal marinho;\r\n4 colheres de sopa de maionese, sem colesterol (60 g);\r\n50 gramas de creme de queijo.', '1. COZINHE AS BERINJELAS EM ÃGUA SALGADA ATÃ‰ AMACIAREM. ESCORRA, PIQUE E RESERVE; \r\n2. REFOGUE O ALHO E A CEBOLA NO AZEITE . JUNTE AS BERINJELAS E REFOGUE POR MAIS 5 MINUTOS;\r\n3. RETIRE DA FRIGIDEIRA E ACRESCENTE A FARINHA DE LINHAÃ‡A. TEMPERE COM SAL E PIMENTA E JUNTE A MAIONESE E O CREME DE QUEIJO; \r\n4. PONHA A MISTURA NO LIQUIDIFICADOR E BATA ATÃ‰ FORMAR UMA PASTA. COLOQUE O PATÃŠ EM RECIPIENTE COM TAMPA E CONSERVE-O NA GELADEIRA.', 11, 3, 12, 156, '2022.11.17-15.25.02jpeg', NULL),
(105, ' MACARRÃƒO AO MOLHO BRANCO', 'Salgado', '1 fatia mÃ©dia de bacon (15 g);\r\n1 unidade de ovo de galinha (45 g);\r\n1 colher de arroz cheia de macarrÃ£o cozido (50 g);\r\n1 lata de creme de leite (300 g);\r\n2 dentes de alho, cru (6 g);\r\n2 colheres de sopa cheias, picado de cebola (20 g);\r\n100 gramas de brÃ³colis cozido.', '1. Cozinhar o macarrÃ£o (preferencia o integral) ao dente;\r\n2. Dourar o bacon em uma frigideira antiaderente, adicionar a cebola, o alho e por ultimo o creme de leite;\r\n3. Adicionar o brÃ³colis, ajustar o sal e em seguida a massa;\r\n4. Servir quente.', 12, 8, 39, 425, '2022.11.17-15.26.24jpeg', NULL),
(106, ' SUCO DE MELANCIA E GENGIBRE', 'Bebida', '3 fatias pequenas de melancia crua sem sementes (300 g);\r\n1 colher de chÃ¡ de farinha de linhaÃ§a;\r\n1 colher de chÃ¡ de gengibre, cru (2 g).', '1. Bater no liquidificador todos os ingredientes, coar e beber a seguir, sem adoÃ§ar.', 22, 3, 2, 108, '2022.11.17-15.27.33jpeg', NULL),
(107, 'TAPENADE', 'Salgado', '50 unidades mÃ©dias de azeitona preta sem caroÃ§o, em conserva, picada (150 g);\r\n1 dente de alho descascado e amassado (3 g);\r\n1 colher de sopa de alcaparra enlatada, escorrida (9 g);\r\n2 colheres de sopa de suco de limÃ£o siciliano;\r\n1 colher de chÃ¡ de raspas de limÃ£o siciliano;\r\n75 gramas de azeite de oliva extra virgem;\r\n1 colher de chÃ¡, moÃ­do de condimento, pimenta do reino (2 g).', '1. Coloque a azeitona, o alho, a alcaparra, o suco e as raspas de limÃ£o em um pilÃ£o ou processador de alimentos. Acrescente uma colher de sopa de azeite e bata formando uma mistura homogÃªnea. VÃ¡ adicionando aos poucos o restante do azeite atÃ© obter uma pasta espessa;\r\n2. Coloque a azeitona, o alho, a alcaparra, o suco e as raspas de limÃ£o em um pilÃ£o ou processador de alimentos. Acrescente uma colher de sopa de azeite e bata formando uma mistura homogÃªnea. VÃ¡ adicionando aos poucos o restante do azeite atÃ© obter uma pasta espessa;\r\n3. Prove, tempere com pimenta-do-reino preta moÃ­da na hora;\r\n4. O antepasto pode ser mantido em geladeira por atÃ© 4 dias em recipiente de vidro limpo, esterilizado e tampado.', 5, 1, 42, 387, '2022.11.17-15.29.19jpeg', NULL),
(108, ' CHEESECAKE', 'Doce', '380 gramas de farinha de trigo peneirada;\r\n220 gramas de manteiga sem sal, gelada;\r\n80 gramas de gema de ovo de galinha peneirada (para a massa) + 80 gramas de gema de ovo de galinha peneirada (para o recheio);\r\n6 gramas de Ã¡gua (1 colher de chÃ¡);\r\n75 gramas de aÃ§Ãºcar refinado (para a massa) + 100 gramas de aÃ§Ãºcar (para o recheio);\r\n6 gramas de conhaque (1 colher de chÃ¡) ou de cafÃ©;\r\n600 gramas de queijo, \"cream cheese\";\r\n100 gramas de clara de ovo de galinha, batidas em neve;\r\n100 gramas de creme de leite;\r\n2 gramas de suco concentrado de limÃ£o (1 colher de cafÃ©);\r\n1 colher de cafÃ© de casca de limÃ£o, em raspas (2 g);\r\n800 gramas de coulis de Morango.', '1. Para a Massa Peneire a farinha. Corte a manteiga em pedaÃ§os. Misture a manteiga e a farinha com as pontas dos dedos, sem ativar o glÃºten. Abra um buraco no meio para misturar os demais ingredientes. Misture formando uma massa lisa e homogÃªnea, sem pedaÃ§os de manteiga. Cubra com filme plÃ¡stico e deixe descansar em geladeira atÃ© esfriar a massa. Com a massa gelada, enforme, fure com um garfo, leve para assar a 180Â°C, atÃ© doura;\r\n2. Para o Recheio Bata as 80 gramas de gemas com os 100 gramas de aÃ§Ãºcar atÃ© aumentar de volume e clarear. Adicione o queijo, o creme de leite e o suco de limÃ£o. Misture delicadamente com as claras batidas em neve;\r\n3. Para o Recheio Bata as 80 gramas de gemas com os 100 gramas de aÃ§Ãºcar atÃ© aumentar de volume e clarear. Adicione o queijo, o creme de leite e o suco de limÃ£o. Misture delicadamente com as claras batidas em neve;\r\n4. Para o Recheio Bata as 80 gramas de gemas com os 100 gramas de aÃ§Ãºcar atÃ© aumentar de volume e clarear. Adicione o queijo, o creme de leite e o suco de limÃ£o e as raspas. Misture delicadamente com as claras batidas em neve;\r\n5. Use uma assadeira de fundo removÃ­vel para a montagem. ApÃ³s rechear, volte ao forno por mais 5 a 8 minutos. Deixe gelar. Sirva com o Coulis de Morango.', 27, 5, 19, 292, '2022.11.17-15.31.38jpeg', NULL),
(109, 'PETIT GÃ‚TEAU DE CHOCOLATE', 'Doce', '400 gramas de chocolate meio amargo;\r\n130 gramas de manteiga sem sal;\r\n250 gramas de ovo de galinha cru;\r\n120 gramas de aÃ§Ãºcar refinado;\r\n20 gramas de farinha de trigo;\r\n10 gramas de cacau em pÃ³;\r\n100 gramas de gema de ovo de galinha crua.', '1. VocÃª vai precisar de 15 forminhas para petit gÃ¢teau untadas com margarina ou desmoldante e polvilhadas com farinha de trigo e cacau;\r\n2. Derreta o chocolate e a manteiga em banho-maria. Reserve;\r\n3. Bata os ovos com o aÃ§Ãºcar atÃ© aumentar de volume e clarear. Agregue a farinha e o cacau em pÃ³. Misture o chocolate e a manteiga derretidos;\r\n4. Distribua nas forminhas (deixe 1 dedo abaixo do limite da forma). Deixe 15 minutos no congelador;\r\n5. Leve ao forno para assar a 220ÂºC a 250ÂºC por 5 a 8 minutos (mÃ¡ximo 15 minutos).', 38, 7, 28, 406, '2022.11.17-15.33.08jpeg', NULL),
(110, 'FOCACCIA', 'Salgado', '500 gramas de farinha de trigo + 10 gramas de melhorador de farinha;\r\n5 gramas de aÃ§Ãºcar refinado;\r\n5 gramas de sal dietÃ©tico;\r\n10 gramas de fermento em pÃ³;\r\n30 gramas de azeite de oliva extra virgem;\r\n280 gramas de Ã¡gua morna (32ÂºC).', '1. Ative o fermento com 30 gramas de farinha e 80 gramas de Ã¡gua. Cubra. Aguarde 10 a 20 minutos atÃ© estar com aspecto de esponja;\r\n2. Acrescente os demais ingredientes. Misture, sove por 10 minutos. Deixe descansar 20 a 30 minutos;\r\n3. Abra a massa com espessura de 1 dedo. Coloque numa assadeira untada com azeite. FaÃ§a depressÃµes na massa com as pontas dos dedos. Pincele azeite. Polvilhe sal. Deixe descansar 15 minutos;\r\n4. Asse em forno prÃ©-aquecido a 220ÂºC por 20 a 25 minutos, atÃ© dourar.', 46, 6, 4, 253, '2022.11.17-15.35.09jpeg', NULL),
(111, ' CROISSANT', 'doce/Salgado', '6 gramas de fermento em pÃ³;\r\n30 gramas de farinha de trigo;\r\n80 gramas de Ã¡gua morna (32ÂºC);\r\n50 gramas de ovo de galinha cru;\r\n250 gramas de farinha de trigo;\r\n25 gramas de manteiga sem sal;\r\n50 gramas de leite de vaca integral;\r\n3 gramas de sal.', '1. Ative o fermento misturando Ã¡gua morna e 50 gramas de farinha de trigo. Cubra. Deixe descansar 10 a 20 minutos, atÃ© estar com aspecto de esponja;\r\n2. Misture os demais ingredientes. Cubra cm filme plÃ¡stico e deixe descansar 30 minutos em geladeira (ideal 4 horas);\r\n3. Abra a massa como um retÃ¢ngulo. Espalhe metade da manteiga (ponto pommade) no centro. Dobre como um envelope. Deixe descansar 20 minutos na geladeira, coberto por filme plÃ¡stico. Repita esta etapa mais uma vez;\r\n4. Abra a massa como um retÃ¢ngulo e corte triÃ¢ngulos de massa. FaÃ§a uma incisÃ£o de 1cm no meio da base do triÃ¢ngulo. Enrole (se deseja rechear, coloque uma colher de recheio na base da massa, pode ser doce ou salgado). Curve as pontas. Leve para assar em forno prÃ©-aquecido;\r\n5. Se for rechear com chocolate, envolva o doce em manteiga, depois na farinha de trigo, para proteger.', 44, 7, 7, 266, '2022.11.17-15.37.23jpeg', NULL),
(112, 'MOLHO DE TOMATE', 'Salgado', '500 gramas de tomate, maduro, picado em cubos, sem pele nem sementes, cru;\r\n60 gramas de cebola branca, crua, picada em cubos;\r\n2 colheres de sopa de azeite de oliva extra virgem (16 g);\r\n1 dente de alho amassado;\r\n5 folhas de manjericÃ£o, fresco;\r\n1/2 colher de chÃ¡ de folhas de tomilho, fresco;\r\n1/2 colher de chÃ¡ de louro, em pÃ³;\r\nPimenta do reino preta, moÃ­da na hora (Ã  gosto);\r\nSal (Ã  gosto).', '1. Em uma panela alta, doure a cebola no azeite. Acrescente o alho, refogue. Junte os tomates. Tempere com manjericÃ£o fresco, folhas de tomilho frescas, louro em pÃ³, pimenta do reino preta moÃ­da na hora e sal. Cozinhe em fogo baixo, por 40 a 60 minutos, atÃ© atingir consistÃªncia levemente espessa. Desligue o fogo, estÃ¡ pronto para uso;\r\n2. Armazene em pote de vidro, esterilizado, preferencialmente escuro e com tampa. Mantenha em geladeira por atÃ© 5 dias, no congelador por atÃ© 30 dias, ou ainda, no freezer por atÃ© 90 dias. Use uma etiqueta para colocar a data de preparo e especificar a receita.', 5, 1, 3, 45, '2022.11.17-15.38.53jpeg', NULL),
(113, ' IOGURTE GREGO CASEIRO', 'Doce', '1000 gramas de leite de vaca integral;\r\n170 gramas de iogurte natural integral.', '1. Em uma panela, aqueÃ§a o leite atÃ© 90ÂºC. Transfira para uma vasilha grossa. Mexa atÃ© resfriar a 45ÂºC. Coloque uma concha do leite no iogurte. Mexa bem. Continue atÃ© resfriar a 35ÂºC. Junte o leite no iogurte. Mexa. Cubra com filme plÃ¡stico, depois embrulhe num pano de prato. Armazene numa bolsa ou caixa tÃ©rmica. Aguarde 8 a 12 horas. Neste ponto temos um iogurte natural tradicional;\r\n2. Para o iogurte grego, transfira para um pano de prato e deixe dessorar em geladeira cerca de 2 a 5 horas.', 12, 10, 9, 172, '2022.11.17-15.40.46jpeg', NULL),
(114, 'LEITE DE AMÃŠNDOAS', 'Bebida', '1 xÃ­cara de chÃ¡ de amÃªndoa sem pele (145 g);\r\n4 xÃ­caras de chÃ¡ de Ã¡gua mineral ou filtrada (948 g)', '1. Deixar as amÃªndoas de molho por uma noite na geladeira, cobertas com 1 xÃ­cara de chÃ¡ de Ã¡gua;\r\n2. No dia seguinte, dispensar a Ã¡gua e bater as amÃªndoas com 3 xÃ­caras de Ã¡gua;\r\n3. A mistura deve ser coada dentro de uma jarra com um pano de prato limpo. Depois de coado, vai virar um leite branco e lisinho;\r\n4. Fica Ã³timo com mel, frutas, cacau em pÃ³ solÃºvel ou cafÃ©;\r\n5. O que sobrar em cima do pano de prato pode ser reaproveitado e usado em vÃ¡rias receitas, como bolos, biscoitos e queijos veganos.', 3, 4, 10, 110, '2022.11.17-15.42.20jpeg', NULL),
(115, 'OVOS MEXIDOS', 'Salgado', '10 unidades de ovo de galinha (450 g);\r\n1 ponta de faca de manteiga, sem sal (5 g);\r\n1 colher de sobremesa de azeite de oliva extra virgem (5 g);\r\nPimenta dedo-de-moÃ§a picadinha, 1 a 2 unidades (Ã  gosto);\r\n1 colher de chÃ¡ de gengibre, cru (2 g);\r\n1 colher de sopa, picada de cebolinha verde, crua (6 g);\r\n1 grama de sal dietÃ©tico;\r\n1 fatia mÃ©dia de queijo minas frescal (30 g).', '1. Quebre os ovos, um a um, em uma tigelinha. Ã€ medida que cada ovo for quebrado, passe-o para uma tigela maior, atÃ© juntar os 10 ovos. FaÃ§a isso para evitar quebrar todos em uma tigela e, no meio do caminho, abrir um ovo estragado. Tempere com sal e pimenta-do-reino moÃ­da na hora. Misture com uma colher;\r\n2. Leve uma frigideira mÃ©dia ao fogo mÃ©dio. Quando aquecer, adicione a manteiga, o azeite, a pimenta dedo-de-moÃ§a e o gengibre. Em seguida, reduza o fogo para o mÃ­nimo e junte os ovos. Com uma colher de silicone, misture de vez em quando;\r\n3. Quando os ovos estiverem comeÃ§ando a endurecer, adicione o queijo em cubos e a cebolinha picada. Continue misturando e, quando os ovos estiverem quase cozidos, mas ainda tiverem um pouco de lÃ­quido, desligue o fogo. O calor da frigideira e do alimento terminarÃ¡ de cozinhar os ovos e assim eles ficarÃ£o molinhos e cremosos.', 1, 11, 12, 158, '2022.11.17-15.43.47jpeg', NULL);

--
-- Indexes for dumped tables
--

--
-- Indexes for table `cadastro`
--
ALTER TABLE `cadastro`
  ADD PRIMARY KEY (`idlogin`),
  ADD UNIQUE KEY `emailUnix` (`email`);

--
-- Indexes for table `receitas`
--
ALTER TABLE `receitas`
  ADD PRIMARY KEY (`idreceitas`),
  ADD KEY `loginFK` (`loginid`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `cadastro`
--
ALTER TABLE `cadastro`
  MODIFY `idlogin` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=82;

--
-- AUTO_INCREMENT for table `receitas`
--
ALTER TABLE `receitas`
  MODIFY `idreceitas` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=116;

--
-- Constraints for dumped tables
--

--
-- Constraints for table `receitas`
--
ALTER TABLE `receitas`
  ADD CONSTRAINT `loginFK` FOREIGN KEY (`loginid`) REFERENCES `cadastro` (`idlogin`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
